Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2018-05, with the labels that each got.

#273 hotfix(interventions): add missing serviceName param
  client/app/dedicated/server/intervention/dedicated-server-intervention.controller.js
Labels: bug

#272 fix(modal): remove aria-hidden and tab-index
  client/app/account/billing/billing.html
  client/app/account/billing/common/index.html
  client/app/account/billing/fidelity/billing-fidelity.html
  client/app/account/billing/history/billing-history.html
  client/app/account/billing/ovhAccount/billing-ovhAccount.html
  client/app/account/user/user.html
  client/app/cdn/dedicated/cdn-dedicated.html
  client/app/components/feedback/feedback.html
  client/app/components/working-status/working-status.html
  client/app/dedicated/housing/dedicated-housing.html
  client/app/dedicated/nas/nas.html
  client/app/dedicated/server/dedicated-server.html
  client/app/dedicatedCloud/datacenter/dedicatedCloud-datacenter.html
  client/app/dedicatedCloud/dedicatedCloud.html
  client/app/index.ejs
  client/app/ip/ip.html
  client/app/license/detail/license-detail.html
  client/app/license/license.html
  client/app/license/order/license-order.html
Labels: bug

#213 fix(dedicated server ftp backup): add oui-action-menu
  client/app/dedicated/server/ftp-backup/access/delete/dedicated-server-ftp-backup-access-delete.controller.js
  client/app/dedicated/server/ftp-backup/access/delete/dedicated-server-ftp-backup-access-delete.html
  client/app/dedicated/server/ftp-backup/access/update/dedicated-server-ftp-backup-access-update.controller.js
  client/app/dedicated/server/ftp-backup/access/update/dedicated-server-ftp-backup-access-update.html
  client/app/dedicated/server/ftp-backup/activate/dedicated-server-ftp-backup-activate.html
  client/app/dedicated/server/ftp-backup/dedicated-server-ftp-backup.controller.js
  client/app/dedicated/server/ftp-backup/dedicated-server-ftp-backup.html
  client/app/dedicated/server/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#264 feat(billing): add option to set paper or paperless for bills
  client/app/account/billing/common/messageParser.js
  client/app/account/billing/history/billing-history.controller.js
  client/app/account/billing/history/billing-history.html
  client/app/account/billing/history/validateInvoicesChange/billing-history-validateInvoicesChange.controller.js
  client/app/account/billing/history/validateInvoicesChange/billing-history-validateInvoicesChange.html
  client/app/account/billing/translations/Messages_fr_FR.xml
  yarn.lock
Labels: feature, quality check ok

#263 fix(account): improve layout
  client/app/account/index.html
Labels: bug

#270 feat: deleted "User Subscriptions" section
  client/app/account/user/subscriptions/user-subscriptions.controller.js
  client/app/account/user/subscriptions/user-subscriptions.html
  client/app/account/user/subscriptions/user-subscriptions.service.js
  client/app/account/user/user.module.js
  client/app/components/sidebar-menu/account/sidebar-menu-account.config.js
  client/app/components/user/session/user-session.service.js
Labels: enhancement, quality check ok

#277 Fix/interventions
  client/app/dedicated/server/intervention/dedicated-server-intervention.controller.js
  client/app/dedicated/server/intervention/dedicated-server-intervention.html
  client/app/dedicated/server/translations/Messages_fr_FR.xml
Labels: enhancement, quality check

#278 fix(dns): replace table with oui-datagrid
  client/app/dedicated/server/dedicated-server.service.js
  client/app/dedicated/server/dns/dedicated-server-dns.controller.js
  client/app/dedicated/server/dns/dedicated-server-dns.html
Labels: enhancement, quality check ok

#280 Refactor/cdn ssl add modal
  client/app/cdn/dedicated/manage/cdn-dedicated-manage.html
  client/app/cdn/dedicated/manage/ssl/add/cdn-dedicated-ssl-add.controller.js
  client/app/cdn/dedicated/manage/ssl/add/cdn-dedicated-ssl-add.html
  client/app/cdn/dedicated/manage/ssl/add/cdn-dedicated-ssl-add.routes.js
  client/app/cdn/dedicated/manage/ssl/add/translations/Messages_fr_FR.xml
  client/app/cdn/dedicated/manage/ssl/cdn-dedicated-manage-ssl.html
  yarn.lock
Labels: enhancement, quality check ok

#287 Refactor/cdn ssl generate
  client/app/cdn/dedicated/manage/ssl/add/cdn-dedicated-ssl-add.html
  client/app/cdn/dedicated/manage/ssl/cdn-dedicated-manage-ssl.html
  client/app/cdn/dedicated/manage/ssl/generate/cdn-dedicated-ssl-generate.controller.js
  client/app/cdn/dedicated/manage/ssl/generate/cdn-dedicated-ssl-generate.html
  client/app/cdn/dedicated/manage/ssl/generate/cdn-dedicated-ssl-generate.routes.js
  client/app/cdn/dedicated/manage/ssl/generate/translations/Messages_fr_FR.xml
  client/app/components/ovh-ui-angular/ovh-ui-angular.module.js
Labels: enhancement, quality check ok

#288 hotfix(license): fix spla active state
  client/app/dedicatedCloud/dedicatedCloud.service.js
Labels: bug

#294 Refactor/cdn ssl update modal
  client/app/cdn/dedicated/manage/ssl/add/cdn-dedicated-ssl-add.html
  client/app/cdn/dedicated/manage/ssl/cdn-dedicated-manage-ssl.html
  client/app/cdn/dedicated/manage/ssl/cdn-dedicated-manage-ssl.routes.js
  client/app/cdn/dedicated/manage/ssl/generate/cdn-dedicated-ssl-generate.controller.js
  client/app/cdn/dedicated/manage/ssl/translations/Messages_fr_FR.xml
  client/app/cdn/dedicated/manage/ssl/update/cdn-dedicated-ssl-update.controller.js
  client/app/cdn/dedicated/manage/ssl/update/cdn-dedicated-ssl-update.html
  client/app/cdn/dedicated/manage/ssl/update/cdn-dedicated-ssl-update.routes.js
  client/app/cdn/dedicated/manage/ssl/update/translations/Messages_fr_FR.xml
  client/app/cdn/dedicated/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#296 refactor(cdn dedicated ssl): refactor delete ssl modal
  client/app/cdn/dedicated/manage/ssl/cdn-dedicated-manage-ssl.html
  client/app/cdn/dedicated/manage/ssl/delete/cdn-dedicated-ssl-delete.controller.js
  client/app/cdn/dedicated/manage/ssl/delete/cdn-dedicated-ssl-delete.html
  client/app/cdn/dedicated/manage/ssl/delete/cdn-dedicated-ssl-delete.routes.js
  client/app/cdn/dedicated/manage/ssl/delete/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#311 fix(): display message for enterprise customer
  client/app/dedicatedCloud/datacenter/datastore/orderUS/dedicatedCloud-datacenter-datastore-orderUS.html
  client/app/dedicatedCloud/datacenter/host/orderUS/dedicatedCloud-datacenter-host-orderUS.html
  client/app/ip/ip/agoraOrder/ip-ip-agoraOrder.html
  client/app/license/order/license-order.html
Labels: bug

#240 feat(vrack): add sidebar menu item
  Gruntfile.js
  client/app/components/feature-availability/feature-availability.service.js
  client/app/components/sidebar-menu/sidebar-menu.config.js
  constants.config.js
Labels: feature, quality check ok

#321 fix(trads): fix broken trads
  client/app/ip/translations/Messages_cs_CZ.xml
  client/app/ip/translations/Messages_de_DE.xml
  client/app/ip/translations/Messages_en_ASIA.xml
  client/app/ip/translations/Messages_en_AU.xml
  client/app/ip/translations/Messages_en_CA.xml
  client/app/ip/translations/Messages_en_GB.xml
  client/app/ip/translations/Messages_en_SG.xml
  client/app/ip/translations/Messages_en_US.xml
  client/app/ip/translations/Messages_es_ES.xml
  client/app/ip/translations/Messages_es_US.xml
  client/app/ip/translations/Messages_fi_FI.xml
  client/app/ip/translations/Messages_fr_CA.xml
  client/app/ip/translations/Messages_fr_FR.xml
  client/app/ip/translations/Messages_it_IT.xml
  client/app/ip/translations/Messages_lt_LT.xml
  client/app/ip/translations/Messages_nl_NL.xml
  client/app/ip/translations/Messages_pl_PL.xml
  client/app/ip/translations/Messages_pt_PT.xml
Labels: bug

#325 fix(ipfo order): minor html fix
  client/app/ip/ip/order/PCC.html
  client/app/ip/ip/order/VPS.html
  client/app/ip/ip/order/durations.html
Labels: bug

#319 fix(user rights): replace table with oui-datagrid
  client/app/dedicatedCloud/user/rights/dedicatedCloud-user-rights.controller.js
  client/app/dedicatedCloud/user/rights/dedicatedCloud-user-rights.html
  client/app/dedicatedCloud/user/rights/edit/dedicatedCloud-user-rights-edit.html
Labels: enhancement, quality check ok

#318 fix(cdn dedicated ssl): use type on oui-modal to display warning
  client/app/cdn/dedicated/manage/ssl/add/cdn-dedicated-ssl-add.controller.js
  client/app/cdn/dedicated/manage/ssl/add/cdn-dedicated-ssl-add.html
  client/app/cdn/dedicated/manage/ssl/delete/cdn-dedicated-ssl-delete.controller.js
  client/app/cdn/dedicated/manage/ssl/delete/cdn-dedicated-ssl-delete.html
  client/app/cdn/dedicated/manage/ssl/delete/translations/Messages_fr_FR.xml
  client/app/cdn/dedicated/manage/ssl/generate/cdn-dedicated-ssl-generate.controller.js
  client/app/cdn/dedicated/manage/ssl/generate/cdn-dedicated-ssl-generate.html
  client/app/cdn/dedicated/manage/ssl/update/cdn-dedicated-ssl-update.controller.js
  client/app/cdn/dedicated/manage/ssl/update/cdn-dedicated-ssl-update.html
  client/app/cdn/dedicated/manage/ssl/update/translations/Messages_fr_FR.xml
  yarn.lock
Labels: enhancement

#342 feat(): update otrs module
  yarn.lock
Labels: feature, quality check ok

#345 fix(translations): en_ASIA language now display the right language
  Assets.js
  Gruntfile.js
  tasks/xml2json.js
  yarn.lock
Labels: bug

#347 Feat/Consent update in user profile
  client/app/account/user/components/newAccountForm/field/new-account-form-field-component.html
  client/app/account/user/components/newAccountForm/new-account-form-component.html
  client/app/account/user/components/newAccountForm/new-account-form-component.js
  client/app/account/user/infos/user-infos.service.js
  client/app/account/user/newAccountForm/translations/Messages_fr_FR.xml
Labels: feature, quality check

#334 fix(cdn domain): fix stats chart labels
  client/app/cdn/dedicated/domain/statistics/cdn-dedicated-domain-statistics.controller.js
Labels: bug, quality check ok

#333 fix(ipmi): fix sol guide
  client/app/dedicated/server/ipmi/dedicated-server-ipmi.html
  client/app/dedicated/server/translations/Messages_fr_FR.xml
  constants.config.js
Labels: bug, quality check ok

#348 fix(useraccount): fix account creation link
  client/app/account/user/contacts/user-contacts.controller.js
  constants.config.js
Labels: bug, quality check ok

#360 refactor(account user advanced): rewrite controller as class
  client/app/account/user/advanced/user-advanced.constants.js
  client/app/account/user/advanced/user-advanced.controller.js
  client/app/account/user/advanced/user-advanced.html
  client/app/css/less/module/user-account/advanced.less
  client/app/css/source.less
  yarn.lock
Labels: enhancement

#363 refactor(account user agreements details): rewrite controller as class
  client/app/account/user/agreements/details/user-agreements-details.constants.js
  client/app/account/user/agreements/details/user-agreements-details.controller.js
  client/app/account/user/agreements/details/user-agreements-details.html
  client/app/account/user/agreements/user-agreements.controller.js
  client/app/account/user/agreements/user-agreements.html
  client/app/account/user/agreements/user-agreements.service.js
Labels: enhancement

#364 fix(navbar): remove labs URL
  constants.config.js
Labels: bug

#359 refactor(account user): split routes into their own folders
  client/app/account/user/advanced/user-advanced.constants.js
  client/app/account/user/advanced/user-advanced.controller.js
  client/app/account/user/advanced/user-advanced.html
  client/app/account/user/advanced/user-advanced.routes.js
  client/app/account/user/agreements/details/user-agreements-details.constants.js
  client/app/account/user/agreements/details/user-agreements-details.controller.js
  client/app/account/user/agreements/details/user-agreements-details.html
  client/app/account/user/agreements/details/user-agreements-details.routes.js
  client/app/account/user/agreements/user-agreements.controller.js
  client/app/account/user/agreements/user-agreements.html
  client/app/account/user/agreements/user-agreements.routes.js
  client/app/account/user/agreements/user-agreements.service.js
  client/app/account/user/emails/details/user-emails-details.controller.js
  client/app/account/user/emails/details/user-emails-details.routes.js
  client/app/account/user/emails/user-emails.controller.js
  client/app/account/user/emails/user-emails.routes.js
  client/app/account/user/infos/user-infos.controller.js
  client/app/account/user/infos/user-infos.routes.js
  client/app/account/user/security/user-security.controller.js
  client/app/account/user/security/user-security.routes.js
  client/app/account/user/security/users/users.routes.js
  client/app/account/user/ssh/user-ssh.controller.js
  client/app/account/user/ssh/user-ssh.html
  client/app/account/user/ssh/user-ssh.routes.js
  client/app/account/user/user.controller.js
  client/app/account/user/user.module.js
  client/app/css/less/module/user-account/advanced.less
  client/app/css/source.less
  yarn.lock
Labels: enhancement

#369 feat(agreement): add gdpr trads
  client/app/account/user/translations/Messages_fr_FR.xml
Labels: translation required

#372 fix(ipmi): hide sol for US
  client/app/components/feature-availability/feature-availability.service.js
  client/app/dedicated/server/ipmi/dedicated-server-ipmi.controller.js
  client/app/dedicated/server/ipmi/dedicated-server-ipmi.html
  client/app/dedicated/server/translations/Messages_en_US.xml
  client/app/dedicated/server/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#375 refactor(account user emails): rewrite controllers as classes
  client/app/account/user/emails/details/user-emails-details.controller.js
  client/app/account/user/emails/details/user-emails-details.html
  client/app/account/user/emails/user-emails.controller.js
  client/app/account/user/emails/user-emails.html
  client/app/account/user/emails/user-emails.service.js
  client/app/css/less/module/user-account/emails.less
  client/app/css/source.less
  yarn.lock
Labels: enhancement
