Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2018-11, with the labels that each got.

#760 fix(dedicated server): fix ssh list display
  client/app/dedicated/server/installation/ovh/dedicated-server-installation-ovh.html
Labels: bug

#765 fix(deps): update manager-webpack-config to v2.4.6
  .gitignore
  package.json
  yarn.lock
Labels: bug

#759 feat(navbar): add tracking for assistance and notifications
  client/app/components/navbar/navbar-notification.service.js
  client/app/components/user/session/user-session.service.js
Labels: enhancement, quality check ok

#762 feat(account.tracking): add tracking in account section
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/billing-autoRenew.html
  client/app/account/billing/autoRenew/disableAutoRenewDomains/billing-autoRenew-disableAutoRenewDomains.controller.js
  client/app/account/billing/credits/billing-credits.html
  client/app/account/billing/fidelity/billing-fidelity.html
  client/app/account/billing/fidelity/creditOrder/billing-fidelity-creditOrder.controller.js
  client/app/account/billing/main/history/billing-main-history.controller.js
  client/app/account/billing/main/history/billing-main-history.html
  client/app/account/billing/main/payments/billing-payments.controller.js
  client/app/account/billing/main/payments/billing-payments.html
  client/app/account/billing/mean/add/billing-mean-add.html
  client/app/account/billing/mean/billing-mean.html
  client/app/account/billing/orders/billing-orders.html
  client/app/account/billing/ovhAccount/billing-ovhAccount.controller.js
  client/app/account/billing/ovhAccount/billing-ovhAccount.html
  client/app/account/billing/ovhAccount/retrieve/billing-ovhAccount-retrieve.controller.js
  client/app/account/otrs/otrs.html
  client/app/account/user/advanced/user-advanced.html
  client/app/account/user/agreements/user-agreements.html
  client/app/account/user/components/newAccountForm/field/new-account-form-field-component.js
  client/app/account/user/components/newAccountForm/new-account-form-component.html
  client/app/account/user/components/newAccountForm/new-account-form-component.js
  client/app/account/user/contacts/user-contacts.controller.js
  client/app/account/user/contacts/user-contacts.html
  client/app/account/user/emails/user-emails.html
  client/app/account/user/ip/restriction/add/user-ip-restriction-add.controller.js
  client/app/account/user/password/user-password.controller.js
  client/app/account/user/security/2fa/user-security-2fa.controller.js
  client/app/account/user/security/user-security.html
  client/app/account/user/ssh/add/cloud/user-ssh-add-cloud.controller.js
  client/app/account/user/ssh/add/dedicated/user-ssh-add-dedicated.controller.js
  client/app/account/user/ssh/user-ssh.html
  client/app/account/user/translations/Messages_fr_FR.xml
Labels: enhancement, quality check, translation required

#769 style(navbar): animate notification icon
  client/app/components/navbar/navbar-notification.service.js
  client/app/css/less/common/navbar.less
Labels: enhancement, quality check ok

#770 fix(dedicated.server): delete service
  client/app/dedicated/server/terminate/dedicated-server-terminate.controller.js
Labels: bug, quality check ok

#773 fix(deps): upgrade ovh-ui-kit to v2.22.0
  package.json
  yarn.lock
Labels: bug

#774 fix(deps): upgrade ovh-angular-otrs to v6.3.0
  package.json
  yarn.lock
Labels: bug

#776 fix(deps): upgrade ovh-module-exchange to v9.0.5
  package.json
  yarn.lock
Labels: bug

#779 fix(exchange): upgrade ovh-module-exchange to v9.0.6
  package.json
  yarn.lock
Labels: bug

#780 fix(exchange): upgrade ovh-module-exchange to v9.0.7
  package.json
  yarn.lock
Labels: bug

#787 fix(deps): update manager-webpack-config to v2.4.7
  package.json
  yarn.lock
Labels: bug

#756 Feat/kvm html5 url
  client/app/components/polling/polling.service.js
  client/app/dedicated/server/ipmi/dedicated-server-ipmi.controller.js
  client/app/dedicated/server/ipmi/dedicated-server-ipmi.html
  client/app/dedicated/server/translations/Messages_fr_FR.xml
Labels: feature, quality check ok, translation required

#789 Feat/autorenew renew actions
  client/app/account/billing/autoRenew/billing-autoRenew.constants.js
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/billing-autoRenew.html
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
  client/app/account/billing/autoRenew/domain/billing-autoRenew-domain.html
  client/app/account/billing/autoRenew/hosting/billing-autoRenew-hosting.html
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#785 Fix/work tasks headers
  .eslintignore
  client/app/common/translations/Messages_fr_FR.xml
  client/app/components/product/product.service.js
  client/app/components/working-status/working-status-modal.controller.js
  client/app/components/working-status/working-status-modal.html
  client/app/components/working-status/working-status.directive.js
  client/app/components/working-status/working-status.html
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/dedicated/server/ovh-tasks/dedicated-server-ovh-tasks.component.js
  client/app/dedicated/server/ovh-tasks/dedicated-server-ovh-tasks.html
  client/app/dedicated/server/ovh-tasks/dedicated-server-ovh-tasks.routes.js
  client/app/dedicated/server/ovh-tasks/dedicated-server-ovh-tasks.service.js
  client/app/dedicated/server/ovh-tasks/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#801 refactor(components.ovhtaskfollow): remove unused component
  client/app/components/ovh-task-follow/modal/ovh-task-follow-modal.controller.js
  client/app/components/ovh-task-follow/modal/ovh-task-follow-modal.html
  client/app/components/ovh-task-follow/ovh-task-follow.component.controller.js
  client/app/components/ovh-task-follow/ovh-task-follow.component.js
  client/app/components/ovh-task-follow/ovh-task-follow.html
  client/app/index.html
Labels: :santa: one-manager

#803 fix(ui-angular): ovh-ui-angular patch update
  package.json
  yarn.lock
Labels: bug

#792 fix(autorenew): redirect to exchange on service termination
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/billing-autoRenew.service.js
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
Labels: bug, quality check ok

#796 fix(autorenew): update automatic payment enable/disable conditions
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
Labels: bug, quality check ok

#805 fix(dedicated.ipmi): fix kvm order
  client/app/dedicated/server/dedicated-server.service.js
  client/app/dedicated/server/ipmi/dedicated-server-ipmi.controller.js
Labels: bug, quality check ok

#654 fix(*): terminate domain not working
  client/app/account/billing/confirmTerminate/billing-confirmTerminate.service.js
Labels: bug, quality check ok

#815 Revert "fix(deps): upgrade ovh-module-exchange to v9.1.0"
  package.json
  yarn.lock
Labels: bug

#812 fix(billing): search text capture from url
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
Labels: bug, quality check ok

#819 fix(account): country code update
  client/app/account/user/contacts/update/user-contacts-update.controller.js
  client/app/common/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#794 refactor(components.bytes): move to dedicatedUniverseComponent
  client/app/dedicated/server/traffic/dedicated-server-traffic.service.js
  client/app/dedicatedUniverseComponents/bytes/bytes.filter.js
  client/app/dedicatedUniverseComponents/bytes/index.js
  client/app/dedicatedUniverseComponents/bytes/translations/Messages_fr_FR.xml
  client/app/dedicatedUniverseComponents/index.js
Labels: :santa: one-manager, quality check ok, translation required

#793 refactor(components.bandwidth): move to dedicatedUniverseComponent
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/dedicatedUniverseComponents/bandwidth/bandwidth.filter.js
  client/app/dedicatedUniverseComponents/bandwidth/index.js
  client/app/dedicatedUniverseComponents/bandwidth/translations/Messages_fr_FR.xml
  client/app/dedicatedUniverseComponents/index.js
Labels: :santa: one-manager, quality check ok, translation required

#795 refactor(components.contract): move to dedicatedUniverseComponent
  client/app/account/billing/autoRenew/active/AutoRenewActivation.controller.js
  client/app/account/billing/autoRenew/update/billing-autoRenew-update.controller.js
  client/app/dedicatedUniverseComponents/contract/index.js
  client/app/dedicatedUniverseComponents/contract/user-contract.service.js
  client/app/dedicatedUniverseComponents/index.js
  client/app/user-contracts/modal/user-contracts-accept.controller.js
  client/app/user-contracts/user-contracts.controller.js
Labels: :santa: one-manager, quality check ok

#797 refactor(components.price): move to dedicatedUniverseComponent
  client/app/account/billing/ovhAccount/retrieve/billing-ovhAccount-retrieve.html
  client/app/dedicated/server/bandwidth-vrack/order/dedicated-server-bandwidth-vrack-order.html
  client/app/dedicated/server/bandwidth/order/dedicated-server-bandwidth-order.html
  client/app/dedicated/server/kvm/order/dedicated-server-kvm-order.html
  client/app/dedicated/server/pro-use/order/dedicated-server-pro-use-order.html
  client/app/dedicated/server/traffic/order/dedicated-server-traffic-order.html
  client/app/dedicated/server/usb-storage/order/dedicated-server-usb-storage-order.html
  client/app/dedicatedCloud/resource/upgrade/dedicatedCloud-resource-upgrade.html
  client/app/dedicatedUniverseComponents/index.js
  client/app/dedicatedUniverseComponents/price/index.js
  client/app/dedicatedUniverseComponents/price/price.filter.js
  client/app/dedicatedUniverseComponents/price/translations/Messages_fr_FR.xml
  client/app/ip/ip/order/durations.html
  client/app/ip/ip/order/durationsPCC.html
  client/app/ip/ip/order/migrate/ip-ip-order-migrate.html
  client/app/license/order/license-order.html
  client/app/license/upgrade/license-upgrade.html
Labels: :santa: one-manager, quality check ok, translation required

#814 fix(alignment-fix): licence order table fix
  client/app/license/order/license-order.html
Labels: bug, quality check ok

#827 fix(deps): upgrade npm-run-all to v4.1.5
  package.json
  yarn.lock
Labels: bug

#832 fix(account.user.security.sms): re-enable sms
  client/app/account/user/security/sms/user-security-sms.service.js
Labels: bug

#824 Feat/autorenew payment mean
  client/app/account/billing/autoRenew/billing-autoRenew.constants.js
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/warnPaymentMean/billing-autoRenew-warnPaymentMean.controller.js
  client/app/account/billing/autoRenew/warnPaymentMean/billing-autoRenew-warnPaymentMean.html
  client/app/account/billing/autoRenew/warnPendingDebt/billing-autoRenew-warnPendingDebt.html
  client/app/account/billing/billingApp.module.js
  client/app/account/billing/main/history/balance/billing-history-balance.controller.js
  client/app/account/billing/main/history/balance/billing-history-balance.html
  client/app/account/billing/mean/billing-mean.html
  client/app/account/billing/translations/Messages_fr_FR.xml
  package.json
  yarn.lock
Labels: enhancement, quality check ok, translation required

#799 refactor(components.loader): replace loader by oui-spinner
  client/app/account/user/contacts/request/received/user-contacts-request-received.html
  client/app/account/user/contacts/request/send/user-contacts-request-send.html
  client/app/account/user/contacts/update/user-contacts-update.html
  client/app/components/loader/loader.directive.js
  client/app/components/loader/loader.html
  client/app/ip/ip/antispam/ip-ip-antispam.html
  client/app/ip/ip/mitigation/statistics/ip-ip-mitigation-statistics.html
Labels: :santa: one-manager, quality check ok

#806 refactor(components.tabs): move to dedicatedUniverseComponents
  client/app/components/directives.module.js
  client/app/components/tabs/tabs.directive.js
  client/app/dedicated/housing/dedicated-housing.html
  client/app/dedicated/server/dedicated-server.html
  client/app/dedicatedUniverseComponents/index.js
  client/app/dedicatedUniverseComponents/tabs/index.js
  client/app/dedicatedUniverseComponents/tabs/tabs.directive.js
  client/app/dedicatedUniverseComponents/tabs/tabs.html
  client/app/dedicatedUniverseComponents/tabs/translations/Messages_fr_FR.xml
  client/app/ip/ip.html
Labels: :santa: one-manager, quality check ok, translation required

#800 refactor(components.notification): move to dedicatedUniverseComponent
  client/app/components/notification/notification.service.js
  client/app/dedicatedCloud/dedicatedCloud.controller.js
  client/app/dedicatedUniverseComponents/index.js
  client/app/dedicatedUniverseComponents/notification/index.js
  client/app/dedicatedUniverseComponents/notification/notification.service.js
Labels: :santa: one-manager, quality check ok
