Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2018-06, with the labels that each got.

#362 fix(cdn): move header actions
  client/app/cdn/dedicated/domain/cdn-dedicated-domain.html
  client/app/cdn/dedicated/domain/rule/cdn-dedicated-domain-rule.html
  client/app/cdn/dedicated/domain/statistics/cdn-dedicated-domain-statistics.html
  client/app/cdn/dedicated/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#386 fix(dedicated server): hide vrack bandwidth cancel
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
Labels: bug, quality check

#393 fix(order): set good order funnel url
  constants.config.js
Labels: bug

#295 feat: order spla license for US part
  client/app/dedicatedCloud/datacenter/dedicatedCloud-datacenter.html
  client/app/dedicatedCloud/datacenter/license/dedicatedCloud-datacenter-license.routes.js
  client/app/dedicatedCloud/dedicatedCloud.html
  client/app/dedicatedCloud/dedicatedCloud.service.js
  client/app/dedicatedCloud/license/dedicatedCloud-license.controller.js
  client/app/dedicatedCloud/license/dedicatedCloud-license.html
  client/app/dedicatedCloud/license/dedicatedCloud-license.routes.js
  client/app/dedicatedCloud/license/enable/dedicatedCloud-license-enable-us.controller.js
  client/app/dedicatedCloud/license/enable/dedicatedCloud-license-enable-us.html
  client/app/dedicatedCloud/license/enable/dedicatedCloud-license-enable.controller.js
  client/app/dedicatedCloud/license/enable/dedicatedCloud-license-enable.html
  client/app/dedicatedCloud/license/enable/dedicatedCloud-license-enable.routes.js
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: feature, quality check ok

#367 feat(agreement): add more context to gdpr agreements
  client/app/account/user/agreements/details/user-agreements-details.controller.js
  client/app/account/user/agreements/details/user-agreements-details.html
  client/app/account/user/agreements/user-agreements.constant.js
  client/app/account/user/agreements/user-agreements.service.js
  client/app/account/user/translations/Messages_fr_FR.xml
Labels: feature, quality check ok

#411 fix(user account): base url
  client/app/account/user/components/newAccountForm/new-account-form-component.js
Labels: bug

#399 Feat/ip agora order state
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/components/sidebar-menu/translations/Messages_fr_FR.xml
  client/app/ip/ip/agoraOrder/ip-ip-agoraOrder.controller.js
  client/app/ip/ip/agoraOrder/ip-ip-agoraOrder.html
  client/app/ip/ip/agoraOrder/ip-ip-agoraOrder.routes.js
  client/app/ip/ip/ip-ip.html
Labels: enhancement, quality check ok

#416 Fix/sd header
  client/app/dedicated/housing/dedicated-housing.html
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/dedicated/server/dedicated-server.controller.js
  client/app/dedicated/server/dedicated-server.html
  client/app/dedicated/server/dedicated-server.service.js
  client/app/dedicated/server/display-name/display-name.controller.js
  client/app/dedicated/server/display-name/display-name.html
  client/app/dedicated/server/display-name/display-name.routes.js
  client/app/dedicated/server/display-name/translations/Messages_fr_FR.xml
  client/app/dedicated/server/reboot/dedicated-server-reboot.controller.js
  client/app/dedicated/server/reverse-dns/delete/reverse-dns-delete.controller.js
  client/app/dedicated/server/reverse-dns/delete/reverse-dns-delete.html
  client/app/dedicated/server/reverse-dns/delete/reverse-dns-delete.routes.js
  client/app/dedicated/server/reverse-dns/delete/translations/Messages_fr_FR.xml
  client/app/dedicated/server/reverse-dns/update/reverse-dns-update.controller.js
  client/app/dedicated/server/reverse-dns/update/reverse-dns-update.html
  client/app/dedicated/server/reverse-dns/update/reverse-dns-update.routes.js
  client/app/dedicated/server/reverse-dns/update/translations/Messages_fr_FR.xml
  client/app/dedicated/server/statistics/dedicated-server-statistics.controller.js
  client/app/dedicated/server/translations/Messages_fr_FR.xml
  yarn.lock
Labels: bug, quality check ok

#412 fix(pcc): replace table with datagrid in datastore section
  client/app/dedicatedCloud/datacenter/datastore/dedicatedCloud-datacenter-datastore.controller.js
  client/app/dedicatedCloud/datacenter/datastore/dedicatedCloud-datacenter-datastore.html
  client/app/dedicatedCloud/datacenter/datastore/dedicatedCloud-datastore-datacenter.routes.js
Labels: enhancement, quality check ok

#337 fix(): license header actions
  client/app/common/translations/Messages_fr_FR.xml
  client/app/license/license.html
  client/app/license/spla/add/licence-spla-add.routes.js
  client/app/license/spla/add/license-spla-add.controller.js
  client/app/license/spla/add/license-spla-add.html
  client/app/license/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#409 fix(pcc dc host): replace table with datagrid
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.controller.js
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.html
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.routes.js
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#414 fix: won't display autorenew banner and input when not needed
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/billing-autoRenew.html
Labels: bug, quality check ok

#422 fix(dedicated:server): ipmi IP check in US
  client/app/dedicated/server/dedicated-server.service.js
  client/app/dedicated/server/ipmi/dedicated-server-ipmi.controller.js
Labels: bug

#430 Refactor/billing section payments
  Assets.js
  Gruntfile.js
  client/app/account/billing/billingApp.module.js
  client/app/account/billing/main/payments/billing-payments.controller.js
  client/app/account/billing/main/payments/billing-payments.html
  client/app/account/billing/main/payments/billing-payments.routes.js
  client/app/account/billing/main/payments/details/billing-payments-details.controller.js
  client/app/account/billing/main/payments/details/billing-payments-details.html
  client/app/account/billing/main/payments/details/billing-payments-details.routes.js
  client/app/account/billing/main/payments/request/billing-payments-request.controller.js
  client/app/account/billing/main/payments/request/billing-payments-request.routes.js
  package.json
  yarn.lock
Labels: enhancement

#431 refactor(billing): move history to main billing section
  Assets.js
  client/app/account/billing/billingApp.module.js
  client/app/account/billing/main/billing-main.html
  client/app/account/billing/main/history/actions-menu.html
  client/app/account/billing/main/history/balance/billing-history-balance.controller.js
  client/app/account/billing/main/history/balance/billing-history-balance.html
  client/app/account/billing/main/history/balance/billing-history-balance.routes.js
  client/app/account/billing/main/history/billing-history.controller.js
  client/app/account/billing/main/history/billing-history.html
  client/app/account/billing/main/history/billing-history.service.js
  client/app/account/billing/main/history/billing-main-history.controller.js
  client/app/account/billing/main/history/billing-main-history.html
  client/app/account/billing/main/history/billing-main-history.routes.js
  client/app/account/billing/main/history/debt/billing-main-history-debt.routes.js
  client/app/account/billing/main/history/debt/details/billing-main-history-debt-details.controller.js
  client/app/account/billing/main/history/debt/details/billing-main-history-debt-details.html
  client/app/account/billing/main/history/debt/details/billing-main-history-debt-details.routes.js
  client/app/account/billing/main/history/debt/details/translations/Messages_cs_CZ.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_de_DE.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_en_ASIA.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_en_AU.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_en_CA.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_en_GB.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_en_SG.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_en_US.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_es_ES.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_es_US.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_fi_FI.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_fr_CA.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_fr_FR.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_it_IT.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_lt_LT.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_nl_NL.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_pl_PL.xml
  client/app/account/billing/main/history/debt/details/translations/Messages_pt_PT.xml
  client/app/account/billing/main/history/debt/pay/billing-main-history-debt-pay.controller.js
  client/app/account/billing/main/history/debt/pay/billing-main-history-debt-pay.html
  client/app/account/billing/main/history/debt/pay/billing-main-history-debt-pay.routes.js
  client/app/account/billing/main/history/debt/pay/translations/Messages_fr_FR.xml
  client/app/account/billing/main/history/details/billing-history-details.routes.js
  client/app/account/billing/main/history/payDebt/billing-history-payDebt.controller.js
  client/app/account/billing/main/history/payDebt/billing-history-payDebt.html
  client/app/account/billing/main/history/postalMailOptions/billing-main-history-postal-mail-options.controller.js
  client/app/account/billing/main/history/postalMailOptions/billing-main-history-postal-mail-options.html
  client/app/account/billing/main/history/postalMailOptions/billing-main-history-postal-mail-options.routes.js
  client/app/account/billing/main/history/postalMailOptions/translations/Messages_fr_FR.xml
  client/app/account/billing/main/history/translations/Messages_fr_FR.xml
  client/app/account/billing/main/history/validateInvoicesChange/billing-history-validateInvoicesChange.controller.js
  client/app/account/billing/main/history/validateInvoicesChange/billing-history-validateInvoicesChange.html
  client/app/account/billing/paymentMethod/billing-paymentMethod.service.js
  client/app/account/billing/translations/Messages_fr_FR.xml
  client/app/app.routes.js
  client/app/components/angular-ui-router/angular-ui-router.module.js
  client/app/components/sidebar-menu/account/sidebar-menu-account.config.js
  client/app/components/user/user.service.js
  client/app/css/source.less
  package.json
  yarn.lock
Labels: enhancement, quality check

#426 fix(billing): add more information in terminate confirmation message
  client/app/account/billing/autoRenew/delete/billing-autoRenew-delete.controller.js
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#425 fix(license): fix upgrade button redirection
  client/app/license/detail/license-detail.controller.js
  client/app/license/detail/license-detail.html
  client/app/license/detail/license-detail.routes.js
  client/app/license/license.html
  client/app/license/redirection/upgrade/license-redirection-upgrade.controller.js
  client/app/license/redirection/upgrade/license-redirection-upgrade.html
  client/app/license/upgrade/license-upgrade.controller.js
  client/app/license/upgrade/license-upgrade.routes.js
Labels: bug, quality check ok

#438 chore(deps): bump to ovh-ui-kit-bs v1.2.0
  client/app/account/billing/autoRenew/billing-autoRenew.html
  client/app/css/less/common/global.less
  package.json
  yarn.lock
Labels: bug
