Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2018-03, with the labels that each got.

#22 fix(*): update responsive layout
  client/app/index.ejs
  package.json
  yarn.lock
Labels: bug

#30 fix(dedicatedcloud user): display error in user edition
  client/app/dedicatedCloud/user/dedicatedCloud-user.html
Labels: quality check ok

#27 fix(dedicatedcloud): fix progressbar style for operation in todo
  client/app/dedicatedCloud/progressBar.html
Labels: quality check ok

#102 fix(server): fix rtm link language detection
  client/app/dedicated/server/dedicated-server.service.js
Labels: quality check ok

#92 fix(pcc): hide compliante options for us customers until it is available
  client/app/components/feature-availability/feature-availability.service.js
  client/app/dedicatedCloud/dashboard/dedicatedCloud-dashboard.html
  client/app/dedicatedCloud/dedicatedCloud.controller.js
Labels: quality check ok

#97 feat(dedicatedcloud user): nsx user right edit
  client/app/dedicatedCloud/dedicatedCloud.service.js
  client/app/dedicatedCloud/user/dedicatedCloud-user.controller.js
  client/app/dedicatedCloud/user/dedicatedCloud-user.html
  client/app/resources/i18n/dedicatedcloud/Messages_en_GB.xml
  client/app/resources/i18n/dedicatedcloud/Messages_en_US.xml
  client/app/resources/i18n/dedicatedcloud/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#123 fix(dedicatedcloud datacenters): add dropdown-append-to-body
  client/app/dedicatedCloud/datacenters/dedicatedCloud-datacenters.html
Labels: bug, quality check ok

#122 fix(sso auth modal): load translations from npm folder instead of bower
  client/app/components/ovh-angular-sso-auth-modal-plugin/ovh-angular-sso-auth-modal-plugin.module.js
Labels: bug, quality check

#126 feat(multi users): add link in sidebar menu
  client/app/components/sidebar-menu/account/sidebar-menu-account.config.js
  client/app/components/sidebar-menu/account/translations/Messages_en_GB.xml
  client/app/components/sidebar-menu/account/translations/Messages_en_US.xml
  client/app/components/sidebar-menu/account/translations/Messages_fr_FR.xml
Labels: enhancement, quality check

#121 chore: update UI kit
  package.json
  yarn.lock
Labels: bug, quality check ok

#106 fix(dedicated server firewall): prevent multiple alert displaying
  client/app/dedicated/server/firewall/dedicated-server-firewall.controller.js
  client/app/dedicated/server/firewall/dedicated-server-firewall.html
Labels: bug, quality check ok

#124 fix: update route, /me/user has moved to /me/identity/user
  client/app/account/user/security/users/users.service.js
Labels: bug, quality check

#135 fix(dashboard): hide PCC guides from US customers
  client/app/configuration/configuration.controller.js
Labels: bug, quality check ok

#120 us pcc order host & datastore
  client/app/dedicatedCloud/datacenter/datastore/dedicatedCloud-datacenter-datastore.controller.js
  client/app/dedicatedCloud/datacenter/datastore/dedicatedCloud-datacenter-datastore.html
  client/app/dedicatedCloud/datacenter/datastore/dedicatedCloud-datastore-datacenter.routes.js
  client/app/dedicatedCloud/datacenter/datastore/orderUS/dedicatedCloud-datacenter-datastore-orderUS.controller.js
  client/app/dedicatedCloud/datacenter/datastore/orderUS/dedicatedCloud-datacenter-datastore-orderUS.html
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.controller.js
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.html
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.routes.js
  client/app/dedicatedCloud/datacenter/host/orderUS/dedicatedCloud-datacenter-host-orderUS.controller.js
  client/app/dedicatedCloud/datacenter/host/orderUS/dedicatedCloud-datacenter-host-orderUS.html
  client/app/resources/i18n/dedicatedcloud/Messages_en_US.xml
  client/app/resources/i18n/dedicatedcloud/Messages_fr_FR.xml
Labels: feature, quality check

#145 fix(pcc order): fix quantity, fix order button location
  client/app/dedicatedCloud/datacenter/datastore/dedicatedCloud-datacenter-datastore.html
  client/app/dedicatedCloud/datacenter/datastore/orderUS/dedicatedCloud-datacenter-datastore-orderUS.controller.js
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.html
  client/app/dedicatedCloud/datacenter/host/orderUS/dedicatedCloud-datacenter-host-orderUS.controller.js
Labels: bug, quality check

#140 fix(dedicatedcloud dashboard): reduce icon size
  client/app/dedicatedCloud/dashboard/dedicatedCloud-dashboard.html
Labels: enhancement, quality check ok

#139 fix(dedicated server ftp-backup access): update confirm button text
  client/app/dedicated/server/ftp-backup/access/add/dedicated-server-ftp-backup-access-add.html
  client/app/resources/i18n/core/Messages_fr_FR.xml
Labels: bug, quality check ok

#138 fix(*): improve some modals content
  client/app/cdn/dedicated/domain/rule/update/cdn-dedicated-domain-rule-update.html
  client/app/dedicated/nas/details/partition/add/nas-partition-add.controller.js
  client/app/dedicated/nas/details/partition/add/nas-partition-add.html
  client/app/dedicated/server/usb-storage/order/dedicated-server-usb-storage-order.html
  client/app/ip/ip/order/ip-ip-order.html
  client/app/ip/ip/order/migrate/ip-ip-order-migrate.html
  client/app/license/migrate/license-migrate.html
  client/app/resources/i18n/license/Messages_fr_FR.xml
  client/app/resources/i18n/nas/Messages_fr_FR.xml
Labels: bug, quality check ok

#143 fix(account user contacts): TypeError property ovhSubsidiary
  client/app/account/user/contacts/user-contacts.controller.js
Labels: bug, enhancement

#148 fix(dedicatedcloud hds): fix step 3 validation
  client/app/dedicatedCloud/security-options/dedicatedCloud-security-option-order.controller.js
  client/app/dedicatedCloud/security-options/dedicatedCloud-security-option-order.html
Labels: bug, quality check

#152 fix(dedicatedcloud resource upgrade): migrate from bs2 to bs3
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.html
  client/app/dedicatedCloud/dedicatedCloud.html
  client/app/dedicatedCloud/resource/upgrade/dedicatedCloud-resource-upgrade.html
Labels: bug

#154 Fix/mitigation graph
  client/app/css/less/common/datetimepicker.less
  client/app/ip/ip/mitigation/statistics/ip-ip-mitigation-statistics.controller.js
  client/app/ip/ip/mitigation/statistics/ip-ip-mitigation-statistics.html
Labels: bug, quality check ok

#118 fix(firewall rule): avoid errors and set null values to rule attributes
  client/app/ip/ip/firewall/rule/add/ip-ip-firewall-rule-add.controller.js
Labels: bug, quality check ok

#155 chore: bump version of ovh-ui-kit-bs
  Gruntfile.js
  client/app/css/source.less
  package.json
  yarn.lock
Labels: enhancement

#103 fix(housing tasks): replace table with oui-datagrid
  client/app/dedicated/housing/task/dedicated-housing-task.controller.js
  client/app/dedicated/housing/task/dedicated-housing-task.html
Labels: bug

#105 fix(server tasks): replace table with oui-datagrid
  client/app/dedicated/server/task/dedicated-server-task.html
  client/app/dedicated/server/task/dedicated-server-task.js
Labels: bug

#110 fix(pcc datacenters): replace table with oui-datagrid
  client/app/dedicatedCloud/datacenters/dedicatedCloud-datacenters.controller.js
  client/app/dedicatedCloud/datacenters/dedicatedCloud-datacenters.html
Labels: bug

#119 feat(multi users): add account id col
  client/app/account/user/security/users/translations/Messages_en_GB.xml
  client/app/account/user/security/users/translations/Messages_en_US.xml
  client/app/account/user/security/users/translations/Messages_fr_FR.xml
  client/app/account/user/security/users/users.controller.js
  client/app/account/user/security/users/users.html
Labels: feature, quality check ok, translation required
