Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2018-12, with the labels that each got.

#811 Bugfix/duplicate error messages
  client/app/dedicatedCloud/dedicatedCloud.controller.js
  client/app/dedicatedCloud/security/dedicatedCloud-security.controller.js
  client/app/dedicatedCloud/vmware-option/dedicatedCloud-vmware-option.controller.js
Labels: bug, quality check ok

#839 fix(modal-bg-fix): fix modal background
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
Labels: bug, quality check ok

#844 fix(dedicatedcloud): restore dashboard alert
  client/app/dedicatedCloud/dedicatedCloud.controller.js
Labels: bug

#848 refactor(package.json): use start:eu as default start script
  package.json
Labels: enhancement

#849 refactor: install web-universe-components
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: :santa: one-manager, enhancement, quality check ok

#860 Fix/contacts digest loop
  client/app/account/user/contacts/service/user-contacts-service.html
Labels: bug, quality check ok

#859 fix(billing.autorenew): fix exchange renew redirection
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
Labels: bug, quality check ok

#864 feat(components.user.session): remove some assistance menu items for FR
  client/app/account/otrs/translations/Messages_fr_FR.xml
  client/app/common/translations/Messages_fr_FR.xml
  client/app/components/sidebar-menu/translations/Messages_fr_FR.xml
  client/app/components/user/session/user-session.service.js
Labels: bug, quality check ok, translation required

#865 feat(billing.history): change message if there is no debt to pay
  client/app/account/billing/main/history/debt/pay/billing-main-history-debt-pay.controller.js
  client/app/account/billing/main/history/debt/pay/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#879 refactor(babel): remove unused configuration and dependencies
  .babelrc
  package.json
  yarn.lock
Labels: enhancement
