Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2018-04, with the labels that each got.

#166 fix(sidebar): use User.getUrlOf for url retrieval
  client/app/components/sidebar-menu/sidebar-menu.config.js
Labels: bug, quality check ok

#158 fix(account billing refunds): fix payment type info unavailable
  client/app/account/billing/refunds/billing-refunds.html
  client/app/resources/i18n/billing/Messages_en_GB.xml
  client/app/resources/i18n/billing/Messages_en_US.xml
  client/app/resources/i18n/billing/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#133 feat(dedicated server ipmi): add information of os installation in IPMI
  client/app/dedicated/server/ipmi/dedicated-server-ipmi.html
  client/app/resources/i18n/server/Messages_en_GB.xml
  client/app/resources/i18n/server/Messages_en_US.xml
  client/app/resources/i18n/server/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#165 chore(gruntfile): remove open task
  Gruntfile.js
  package.json
  server/app.js
  yarn.lock
Labels: enhancement

#177 fix(license order): replace deprecated loader to oui-spinner
  client/app/license/order/license-order.html
Labels: bug, quality check ok

#173 feat(billing): improve add payment method view
  client/app/account/billing/paymentMethod/add/index.html
  client/app/components/paymentMethod/add/credit-card/billing-payment-method-add-credit-card.html
  client/app/components/paymentMethod/add/credit-card/billing-payment-method-add-credit-card.less
  client/app/resources/i18n/billing/Messages_en_GB.xml
  client/app/resources/i18n/billing/Messages_en_US.xml
  client/app/resources/i18n/billing/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#176 fix(bootstrap fonts path): copy glyphicons font
  Gruntfile.js
  client/app/css/source.less
Labels: bug, quality check ok

#186 fix(license delete): display message if already terminating
  client/app/license/delete/license-delete.controller.js
  client/app/license/license.service.js
  client/app/resources/i18n/license/Messages_en_GB.xml
  client/app/resources/i18n/license/Messages_en_US.xml
  client/app/resources/i18n/license/Messages_fr_FR.xml
Labels: bug, quality check ok

#188 fix(billing confirm terminate): add missing translation key for cpanel
  client/app/resources/i18n/billing/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#157 fix(*): rename services to v6 and v7
  Gruntfile.js
  client/app/account/user/contacts/user-contacts.controller.js
  client/app/app.js
  client/app/index.ejs
  client/app/license/order/license-order.controller.js
  constants.config.js
  package.json
  yarn.lock
Labels: enhancement, quality check ok

#178 feat(account): add menu for managing API credentials
  client/app/account/user/credentials/delete/user-credentials-delete.controller.js
  client/app/account/user/credentials/delete/user-credentials-delete.html
  client/app/account/user/credentials/user-credentials.controller.js
  client/app/account/user/credentials/user-credentials.html
  client/app/account/user/credentials/user-credentials.service.js
  client/app/account/user/user.module.js
  client/app/components/sidebar-menu/account/sidebar-menu-account.config.js
  client/app/components/sidebar-menu/account/translations/Messages_fr_FR.xml
  client/app/resources/i18n/useraccount/Messages_fr_FR.xml
Labels: feature, translation required

#163 Feat/modal layout definition
  client/app/app.js
  client/app/css/less/common/modal.less
  client/app/dedicated/server/monitoring/update/dedicated-server-monitoring-update.controller.js
  client/app/dedicated/server/monitoring/update/dedicated-server-monitoring-update.html
  client/app/dedicated/server/reboot/dedicated-server-reboot.controller.js
  client/app/dedicated/server/reboot/dedicated-server-reboot.html
  client/app/dedicatedCloud/datacenter/backup/disable/dedicatedCloud-datacenter-backup-disable.controller.js
  client/app/dedicatedCloud/datacenter/backup/disable/dedicatedCloud-datacenter-backup-disable.html
  client/app/dedicatedCloud/datacenter/backup/enable/dedicatedCloud-datacenter-backup-enable.controller.js
  client/app/dedicatedCloud/datacenter/backup/enable/dedicatedCloud-datacenter-backup-enable.html
  client/app/dedicatedCloud/datacenter/dedicatedCloud-datacenter.routes.js
  client/app/dedicatedCloud/dedicatedCloud.html
  client/app/dedicatedCloud/dedicatedCloud.routes.js
  client/app/dedicatedCloud/mailing-list/subscribe/dedicatedCloud-mailing-list-subscribe.constant.js
  client/app/dedicatedCloud/mailing-list/subscribe/dedicatedCloud-mailing-list-subscribe.controller.js
  client/app/dedicatedCloud/mailing-list/subscribe/dedicatedCloud-mailing-list-subscribe.html
  client/app/dedicatedCloud/mailing-list/subscribe/dedicatedCloud-mailing-list-subscribe.routes.js
  client/app/dedicatedCloud/mailing-list/subscribe/dedicatedCloud-mailing-list-subscribe.service.js
  client/app/dedicatedCloud/network/dedicatedCloud-network-tabs.controller.js
  client/app/dedicatedCloud/network/dedicatedCloud-network-todo.controller.js
  client/app/dedicatedCloud/network/dedicatedCloud-network.controller.js
  client/app/dedicatedCloud/user/dedicatedCloud-user.html
  client/app/dedicatedCloud/user/rights/dedicatedCloud-user-rights.routes.js
  client/app/resources/i18n/dedicatedcloud/Messages_fr_FR.xml
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement, quality check ok, translation required

#193 fix(dedicatedcloud ml subscribe): remove mock in modal
  client/app/dedicatedCloud/mailing-list/subscribe/dedicatedCloud-mailing-list-subscribe.controller.js
Labels: bug, quality check ok

#199 fix(user contracts): enhance modal layout
  client/app/resources/i18n/user-contracts/Messages_en_GB.xml
  client/app/resources/i18n/user-contracts/Messages_en_US.xml
  client/app/resources/i18n/user-contracts/Messages_fr_FR.xml
  client/app/user-contracts/modal/user-contracts-accept.controller.js
  client/app/user-contracts/modal/user-contracts-accept.html
  client/app/user-contracts/user-contracts.controller.js
Labels: bug, quality check

#190 fix(*): display info to the enterprise customer concerning retail prices
  client/app/dedicatedCloud/datacenter/datastore/orderUS/dedicatedCloud-datacenter-datastore-orderUS.controller.js
  client/app/dedicatedCloud/datacenter/datastore/orderUS/dedicatedCloud-datacenter-datastore-orderUS.html
  client/app/dedicatedCloud/datacenter/host/orderUS/dedicatedCloud-datacenter-host-orderUS.controller.js
  client/app/dedicatedCloud/datacenter/host/orderUS/dedicatedCloud-datacenter-host-orderUS.html
  client/app/ip/ip/agoraOrder/ip-ip-agoraOrder.controller.js
  client/app/ip/ip/agoraOrder/ip-ip-agoraOrder.html
  client/app/license/order/license-order.controller.js
  client/app/license/order/license-order.html
  client/app/resources/i18n/core/Messages_en_GB.xml
  client/app/resources/i18n/core/Messages_en_US.xml
  client/app/resources/i18n/core/Messages_fr_FR.xml
Labels: bug, quality check ok

#202 fix(me-alerts): fix bad links to billing statements
  client/app/components/user/user-alert.controller.js
  client/app/resources/i18n/core/Messages_fr_FR.xml
Labels: bug, quality check ok

#205 fix(sidebar): users management section available in all targets
  client/app/components/sidebar-menu/account/sidebar-menu-account.config.js
  client/app/components/user/session/user-session.service.js
Labels: bug

#206 style(user alert): apply list-unstyled when there is only one alert
  client/app/index.ejs
Labels: bug, quality check ok

#207 Fix/merge datagrid
  client/app/dedicated/housing/task/dedicated-housing-task.controller.js
  client/app/dedicated/housing/task/dedicated-housing-task.html
  client/app/dedicated/server/task/dedicated-server-task.controller.js
  client/app/dedicated/server/task/dedicated-server-task.html
  client/app/dedicated/server/task/dedicated-server-task.js
  client/app/dedicatedCloud/datacenters/dedicatedCloud-datacenters.controller.js
  client/app/dedicatedCloud/datacenters/dedicatedCloud-datacenters.html
  client/app/dedicatedCloud/datacenters/dedicatedCloud-datacenters.routes.js
  client/app/ip/ip/organisation/ip-ip-organisation.controller.js
  client/app/ip/ip/organisation/ip-ip-organisation.html
Labels: enhancement, quality check ok

#204 chore(gruntfile): remove unused checkUrlsInConstants task
  Gruntfile.js
  package.json
  yarn.lock
Labels: enhancement

#209 fix(): temporarily remove debt messages for US
  client/app/account/billing/history/billing-history.controller.js
  client/app/account/billing/history/billing-history.html
  client/app/components/user/user-alert.controller.js
Labels: bug

#212 chore(test): remove useless test folder
  Gruntfile.js
  client/app/test/conf/testacular.midway.conf.js
  client/app/test/midway/appSpec.js
  e2e/tests/main/main.po.js
  e2e/tests/main/main.smoke.spec.js
  package-lock.json
  protractor.conf.js
  tasks/buildIndex.js
  tasks/properties2json.js
Labels: enhancement

#210 refactor(download): remove translator + small refacto
  client/app/account/otrs/detail/otrs-detail.controller.js
  client/app/account/otrs/otrs.app.js
  client/app/download/download-controllers.module.js
  client/app/download/download-services.module.js
  client/app/download/download.app.js
  client/app/download/download.controller.js
  client/app/download/download.html
  client/app/download/download.routes.js
  client/app/download/download.service.js
  client/app/download/translations/Messages_fr_FR.xml
  client/app/resources/i18n/download/Messages_cs_CZ.xml
  client/app/resources/i18n/download/Messages_de_DE.xml
  client/app/resources/i18n/download/Messages_en_ASIA.xml
  client/app/resources/i18n/download/Messages_en_AU.xml
  client/app/resources/i18n/download/Messages_en_CA.xml
  client/app/resources/i18n/download/Messages_en_GB.xml
  client/app/resources/i18n/download/Messages_en_SG.xml
  client/app/resources/i18n/download/Messages_en_US.xml
  client/app/resources/i18n/download/Messages_es_ES.xml
  client/app/resources/i18n/download/Messages_es_US.xml
  client/app/resources/i18n/download/Messages_fi_FI.xml
  client/app/resources/i18n/download/Messages_fr_CA.xml
  client/app/resources/i18n/download/Messages_it_IT.xml
  client/app/resources/i18n/download/Messages_lt_LT.xml
  client/app/resources/i18n/download/Messages_nl_NL.xml
  client/app/resources/i18n/download/Messages_pl_PL.xml
  client/app/resources/i18n/download/Messages_pt_PT.xml
Labels: enhancement

#218 refactor(app): clean app.js file
  client/app/app.js
  client/app/components/ovh-angular-http/ovh-angular-http.module.js
  client/app/components/ovh-angular-sso-auth/ovh-angular-sso-auth.module.js
  client/app/dedicated/dedicated.module.js
  client/app/dedicated/server/dedicated-server.module.js
Labels: enhancement

#219 refactor(ip): replace center with text-center helper
  client/app/ip/ip/antispam/ip-ip-antispam.html
  client/app/ip/ip/mitigation/statistics/ip-ip-mitigation-statistics.html
Labels: bug

#220 style(*): remove unused styles
  client/app/css/less/common/buttonToggle.less
  client/app/css/less/common/changelog.less
  client/app/css/source.less
Labels: enhancement

#221 refactor(components): remove unused components
  client/app/components/availableIp/availableIp.js
  client/app/components/capacity/capacity.js
  client/app/components/distribution/distribution.service.js
  client/app/components/hash/orderObjectBy.js
  client/app/components/paginatedTable/paginatedTable.html
  client/app/components/paginatedTable/paginatedTable.js
  client/app/components/paginatedTable/paginatedTableElement.js
  client/app/components/toggleButton/toggleButton.js
  client/app/components/upload/upload.controller.js
  client/app/components/upload/upload.html
Labels: enhancement

#222 fix(translations): user security section
  client/app/account/user/security/2fa/user-security-2fa.html
  client/app/account/user/security/totp/add/user-security-totp-add.html
Labels: bug

#223 fix(ip): replace i18n with angular-translate
  client/app/ip/ip-lb/backend/add/ip-ip-lb-backend-add.html
  client/app/ip/ip-lb/backend/probe/ip-ip-lb-backend-probe.html
  client/app/ip/ip-lb/ip-ip-lb.html
  client/app/ip/ip/block/move/ip-ip-block-move.html
  client/app/ip/ip/firewall/game/rule/add/ip-ip-firewall-game-rule-add.html
  client/app/ip/ip/ip-ip.html
  client/app/ip/ip/mitigation/statistics/ip-ip-mitigation-statistics.html
  client/app/ip/ip/order/migrate/ip-ip-order-migrate.html
  client/app/ip/ip/organisation/add-or-edit/ip-ip-organisation-add-or-edit.html
  client/app/ip/ip/reverse/add/ip-ip-reverse-add.html
Labels: bug

#224 refactor(account user): remove unused subContacts section
  client/app/account/user/subContacts/add/user-subContacts-add.controller.js
  client/app/account/user/subContacts/add/user-subContacts-add.html
  client/app/account/user/subContacts/delete/user-subContacts-delete.controller.js
  client/app/account/user/subContacts/delete/user-subContacts-delete.html
  client/app/account/user/subContacts/edit/user-subContacts-edit.controller.js
  client/app/account/user/subContacts/edit/user-subContacts-edit.html
  client/app/account/user/subContacts/user-subContacts.controller.js
  client/app/account/user/subContacts/user-subContacts.html
  client/app/account/user/user.module.js
Labels: bug

#226 fix(account user contacts): replace i18n with angular-translate
  client/app/account/user/contacts/request/user-contacts-request.html
  client/app/account/user/contacts/update/user-contacts-update.html
Labels: enhancement

#227 fix(account user password): replace i18n with angular-translate
  client/app/account/user/password/user-password.controller.js
Labels: bug

#228 fix(account user security): replace i18n with angular-translate
  client/app/account/user/security/2fa/user-security-2fa.controller.js
  client/app/account/user/security/sms/edit/user-security-sms-edit.controller.js
  client/app/account/user/security/totp/edit/user-security-totp-edit.controller.js
  client/app/account/user/security/u2f/add/user-security-u2f-add.controller.js
  client/app/account/user/security/u2f/delete/user-security-u2f-delete.controller.js
  client/app/account/user/security/u2f/edit/user-security-u2f-edit.controller.js
Labels: bug

#229 fix(account user otrs): replace i18n with angular-translate
  client/app/account/otrs/detail/otrs-detail.html
  client/app/account/otrs/otrs.app.js
  client/app/account/otrs/otrs.html
Labels: bug

#230 fix(account billing mean): replace i18n with angular-translate
  client/app/account/billing/mean/add/billing-mean-add.html
  client/app/account/billing/mean/billing-mean.html
Labels: bug

#232 fix(account billing autorenew): replace i18n with angular-translate
  client/app/account/billing/autoRenew/common/actions-menu.html
  client/app/account/billing/autoRenew/update/billing-autoRenew-update.controller.js
Labels: bug

#237 fix(i18n): replace translator tr with angular-translate
  client/app/cdn/dedicated/domain/add/cdn-dedicated-domain-add.controller.js
  client/app/dedicated/housing/reboot/dedicated-housing-reboot.controller.js
  client/app/dedicated/nas/details/partition/snapshot/nas-partition-snapshot.controller.js
  client/app/dedicated/nas/order/validation/nas-order-validation.controller.js
  client/app/dedicated/server/ftp-backup/order/dedicated-server-ftp-backup-order.controller.js
  client/app/dedicated/server/installation/gabarit/dedicated-server-installation-gabarit.controller.js
  client/app/dedicated/server/installation/ovh/dedicated-server-installation-ovh.controller.js
  client/app/dedicated/server/kvm/order/dedicated-server-kvm-order.controller.js
  client/app/dedicated/server/monitoring/dedicated-server-monitoring.controller.js
  client/app/dedicated/server/pro-use/order/dedicated-server-pro-use-order.controller.js
  client/app/dedicated/server/statistics/rtm/disk/dedicated-server-statistics-rtm-disk.controller.js
  client/app/dedicated/server/usb-storage/order/dedicated-server-usb-storage-order.controller.js
  client/app/dedicatedCloud/datacenter/host/order/dedicatedCloud-datacenter-host-order.controller.js
  client/app/dedicatedCloud/datacenter/license/enable/dedicatedCloud-datacenter-license-enable.controller.js
  client/app/dedicatedCloud/operation/dedicatedCloud-operation.controller.js
  client/app/dedicatedCloud/user/rights/edit/dedicatedCloud-user-rights-edit.controller.js
  client/app/dedicatedCloud/vmware-option/dedicatedCloud-vmware-option.controller.js
Labels: bug

#236 fix(account user security): replace i18n with angular-translate
  client/app/account/user/security/user-security.html
  client/app/account/user/translations/Messages_fr_FR.xml
Labels: bug

#235 fix(account user contacts): replace i18n with angular-translate
  client/app/account/user/contacts/request/change/user-contacts-request-change.controller.js
Labels: bug

#231 fix(ip): replace scope.tr with angular-translate
  client/app/ip/ip-lb/order/ssl/ip-ip-lb-order-ssl.controller.js
  client/app/ip/ip-lb/order/zone/ip-ip-lb-order-zone.controller.js
  client/app/ip/ip.controller.js
  client/app/ip/ip/block/move/ip-ip-block-move.controller.js
  client/app/ip/ip/firewall/game/rule/add/ip-ip-firewall-game-rule-add.controller.js
  client/app/ip/ip/firewall/game/toggle/ip-ip-firewall-game-toggle.controller.js
  client/app/ip/ip/ip-ip.controller.js
  client/app/ip/ip/order/ip-ip-order.controller.js
  client/app/ip/ip/order/migrate/ip-ip-order-migrate.controller.js
  client/app/ip/ip/virtual-mac/delete/ip-ip-virtual-mac-delete.controller.js
Labels: bug

#239 fix(i18n): replace trpl with ng pluralize
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.html
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: bug

#241 fix(i18n): replace trpl with pluralize in cdn stats section
  client/app/cdn/dedicated/manage/statistics/cdn-dedicated-manage-statistics.html
  client/app/cdn/dedicated/translations/Messages_fr_FR.xml
Labels: bug

#244 fix(account user): replace i18n with angular-translate
  client/app/account/user/contacts/request/change/user-contacts-request-change.html
  client/app/account/user/ip/restriction/add/user-ip-restriction-add.html
  client/app/account/user/ip/restriction/delete/user-ip-restriction-delete.html
  client/app/account/user/password/user-password.html
  client/app/account/user/security/2fa/user-security-2fa.html
  client/app/account/user/security/backupCode/delete/user-security-backupCode.html
  client/app/account/user/security/backupCode/manage/user-security-backupCode-manage.html
  client/app/account/user/security/sms/add/user-security-sms-add.html
  client/app/account/user/security/sms/delete/user-security-sms-delete.html
  client/app/account/user/security/sms/edit/user-security-sms-edit.html
  client/app/account/user/security/totp/add/user-security-totp-add.html
  client/app/account/user/security/totp/delete/user-security-totp-delete.html
  client/app/account/user/security/totp/edit/user-security-totp-edit.html
  client/app/account/user/security/u2f/add/user-security-u2f-add.html
  client/app/account/user/security/u2f/delete/user-security-u2f-delete.html
  client/app/account/user/security/u2f/edit/user-security-u2f-edit.html
  client/app/account/user/ssh/add/cloud/user-ssh-add-cloud.html
  client/app/account/user/ssh/add/dedicated/user-ssh-add-dedicated.html
  client/app/account/user/ssh/delete/user-ssh-delete.html
  client/app/account/user/ssh/view/user-ssh-view.html
Labels: bug

#245 fix(i18n): replace trpl with angular translate for ip section
  client/app/ip/ip/ip-ip.controller.js
  client/app/ip/ip/ip-ip.html
Labels: bug

#246 fix(account billing): replace i18n with angular-translate
  client/app/account/billing/autoRenew/active/billing-autoRenew-active.html
  client/app/account/billing/autoRenew/cancelDelete/billing-autoRenew-cancelDelete.html
  client/app/account/billing/autoRenew/delete/billing-autoRenew-delete.html
  client/app/account/billing/autoRenew/disable/billing-autoRenew-disable.html
  client/app/account/billing/autoRenew/disableAutoRenewDomains/billing-autoRenew-disableAutoRenewDomains.html
  client/app/account/billing/autoRenew/enable/billing-autoRenew-enable.html
  client/app/account/billing/autoRenew/terminateEmail/billing-autoRenew-terminateEmail.html
  client/app/account/billing/autoRenew/terminateHostingWeb/billing-autoRenew-terminateHostingWeb.html
  client/app/account/billing/autoRenew/update/billing-autoRenew-update.html
  client/app/account/billing/fidelity/creditOrder/billing-fidelity-creditOrder.html
  client/app/account/billing/history/payDebt/billing-history-payDebt.html
  client/app/account/billing/mean/delete/billing-mean-delete.html
  client/app/account/billing/ovhAccount/createAlert/billing-ovhAccount-createAlert.html
  client/app/account/billing/ovhAccount/renew/billing-ovhAccount-renew.html
  client/app/account/billing/ovhAccount/retrieve/billing-ovhAccount-retrieve.html
Labels: bug

#250 Fix/i18n wizard confirm
  client/app/cdn/dedicated/backend/order/cdn-dedicated-backend-order.html
  client/app/cdn/dedicated/domain/rule/order/cdn-dedicated-domain-rule-order.html
  client/app/cdn/dedicated/quota/order/cdn-dedicated-quota-order.html
  client/app/components/working-status/working-status-modal.html
  client/app/dedicated/nas/order/validation/nas-order-validation.html
  client/app/dedicated/server/bandwidth-vrack/cancel/dedicated-server-bandwidth-vrack-cancel.html
  client/app/dedicated/server/bandwidth-vrack/order/dedicated-server-bandwidth-vrack-order.html
  client/app/dedicated/server/bandwidth/cancel/dedicated-server-bandwidth-cancel.html
  client/app/dedicated/server/dns/add/dedicated-server-dns-add.html
  client/app/dedicated/server/firewall/order/dedicated-server-firewall-order.html
  client/app/dedicated/server/ftp-backup/access/add/dedicated-server-ftp-backup-access-add.html
  client/app/dedicated/server/installation/choice/dedicated-server-installation-choice.html
  client/app/dedicated/server/installation/progress/dedicated-server-installation-progress.html
  client/app/dedicated/server/kvm/order/dedicated-server-kvm-order.html
  client/app/dedicated/server/traffic/cancel/dedicated-server-traffic-cancel.html
  client/app/dedicated/server/traffic/order/dedicated-server-traffic-order.html
  client/app/dedicatedCloud/datacenter/datastore/order/dedicatedCloud-datacenter-datastore-order.html
  client/app/dedicatedCloud/datacenter/host/order/dedicatedCloud-datacenter-host-order.html
  client/app/dedicatedCloud/price/dedicatedCloud-price.html
  client/app/dedicatedCloud/security-options/dedicatedCloud-security-option-order.html
  client/app/dedicatedCloud/terminate/confirm/dedicatedCloud-terminate-confirm.html
  client/app/dedicatedCloud/vmware-option/disable/dedicatedCloud-vmware-option-disable.html
  client/app/dedicatedCloud/vmware-option/order/dedicatedCloud-vmware-option-order.html
  client/app/ip/ip/antihack/ip-ip-antihack.html
  client/app/ip/ip/arp/ip-ip-arp.html
  client/app/ip/ip/firewall/rule/add/ip-ip-firewall-rule-add.html
  client/app/ip/ip/mitigation/statistics/ip-ip-mitigation-statistics.html
  client/app/ip/ip/organisation/view/ip-ip-organisation-view.html
  client/app/ip/ip/virtual-mac/ip-ip-virtual-mac.html
  client/app/license/redirection/upgrade/license-redirection-upgrade.html
Labels: bug

#251 fix(i18n): fix some translate bindings
  client/app/account/billing/sla/billing-sla.html
  client/app/account/billing/vouchers/billing-vouchers.html
  client/app/account/billing/vouchers/movements/billing-vouchers-movements.html
  client/app/account/user/contacts/request/received/user-contacts-request-received.html
  client/app/account/user/contacts/request/send/user-contacts-request-send.html
  client/app/account/user/contacts/request/user-contacts-request.html
  client/app/account/user/security/users/users.html
  client/app/dedicated/housing/backup/dedicated-housing-backup.html
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/ip/ip-lb/ip-ip-lb.html
Labels: bug

#254 fix(datastore): fix tooltip bindings
  client/app/dedicatedCloud/datacenter/datastore/dedicatedCloud-datacenter-datastore.html
Labels: bug

#208 Feat/us debt
  client/app/account/billing/billingApp.module.js
  client/app/account/billing/components/filters/debtOperationDescription.js
  client/app/account/billing/components/filters/debtOperationStatus.js
  client/app/account/billing/dbtAccount/billing-debtAccount.service.js
  client/app/account/billing/history/actions-menu.html
  client/app/account/billing/history/balance/billing-history-balance.controller.js
  client/app/account/billing/history/balance/billing-history-balance.html
  client/app/account/billing/history/balance/billing-history-balance.routes.js
  client/app/account/billing/history/balance/translations/Messages_en_GB.xml
  client/app/account/billing/history/balance/translations/Messages_en_US.xml
  client/app/account/billing/history/balance/translations/Messages_fr_FR.xml
  client/app/account/billing/history/billing-history.controller.js
  client/app/account/billing/history/billing-history.html
  client/app/account/billing/history/details/billing-history-details.controller.js
  client/app/account/billing/history/details/billing-history-details.html
  client/app/account/billing/history/details/billing-history-details.routes.js
  client/app/account/billing/history/details/translations/Messages_en_GB.xml
  client/app/account/billing/history/details/translations/Messages_en_US.xml
  client/app/account/billing/history/details/translations/Messages_fr_FR.xml
  client/app/account/billing/paymentMethod/add/billing-paymentMethod-add.controller.js
  client/app/account/billing/paymentMethod/add/index.html
  client/app/account/billing/payments/billing-payments.controller.js
  client/app/account/billing/payments/index.html
  client/app/account/billing/payments/request/billing-payments-request.controller.js
  client/app/account/billing/payments/request/billing-payments-request.html
  client/app/account/billing/payments/request/billing-payments-request.routes.js
  client/app/account/billing/payments/request/translations/Messages_en_US.xml
  client/app/account/billing/payments/request/translations/Messages_fr_FR.xml
  client/app/account/billing/services.module.js
  client/app/components/user/user-alert.controller.js
  client/app/resources/i18n/billing/Messages_en_US.xml
  client/app/resources/i18n/billing/Messages_fr_FR.xml
  client/app/resources/i18n/core/Messages_en_US.xml
  package.json
  yarn.lock
Labels: feature, quality check

#255 fix(translate): fix oui-column
  client/app/cdn/dedicated/domain/rule/cdn-dedicated-domain-rule.html
  client/app/dedicated/nas/details/partition/access/nas-partition-access.html
Labels: bug

#258 fix(translation): fix missing license_loading trad
  client/app/dedicated/server/pro-use/order/dedicated-server-pro-use-order.html
  client/app/dedicated/server/usb-storage/order/dedicated-server-usb-storage-order.html
  client/app/license/order/license-order.html
  client/app/license/upgrade/license-upgrade.html
Labels: bug

#259 fix(contact-services): fix buttons translation
  client/app/account/user/contacts/service/user-contacts-service.html
Labels: bug

#261 fix(orders): fix missing translations
  client/app/account/billing/billingApp.module.js
Labels: bug

#260 fix: replace i18n with angular-translate
  client/app/account/billing/translations/Messages_fr_FR.xml
  client/app/common/translations/Messages_fr_FR.xml
  client/app/components/price/priceFilter.js
  client/app/dedicated/server/translations/Messages_fr_FR.xml
  client/app/license/translations/Messages_fr_FR.xml
  package.json
  yarn.lock
Labels: bug
