Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2018-08, with the labels that each got.

#505 fix(dedicatedcloud.datacenter): display host datagrid
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.controller.js
Labels: bug, quality check ok

#508 chore(deps): bump ovh-ui-kit and ovh-ui-kit-bs
  client/app/dedicated/server/ftp-backup/dedicated-server-ftp-backup.html
  client/app/dedicatedCloud/progressBar.html
  package.json
  yarn.lock
Labels: enhancement, ovh-ui-kit

#510 fix(billing.autorenew.update): can deactivate AutoRenew using update …
  client/app/account/billing/autoRenew/update/billing-autoRenew-update.controller.js
Labels: bug, quality check ok

#513 fix(billing.history): sort billing by date asc
  client/app/account/billing/history/billing-history.controller.js
Labels: bug, quality check ok

#517 hotfix(billing.mean.add): SEPA fields separation is now effective per…
  client/app/account/billing/mean/add/billing-mean-add.controller.js
  client/app/account/billing/mean/add/billing-mean-add.html
Labels: bug, quality check ok

#518 fix(server.installation): can add OVH template again
  client/app/dedicated/server/installation/ovh/dedicated-server-installation-ovh.html
Labels: bug, quality check ok

#521 fix(account.user.advanced): update switch template
  client/app/account/user/advanced/user-advanced.html
Labels: bug

#525 fix(billing.paymentmethod.add): upgrade expiration date list
  client/app/account/billing/paymentMethod/add/index.html
  client/app/components/paymentMethod/vantiv/billing-vantiv.factory.js
Labels: bug, quality check ok

#512 fix/auto renew sms list item
  client/app/account/billing/autoRenew/common/actions-menu-email-domain.html
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
Labels: bug, quality check ok

#529 fix(billing.payasyougo): handle empty route.url and route.path
  client/app/account/billing/main/payAsYouGo/billing-main-pay-as-you-go.html
  client/app/components/services/services.service.js
Labels: bug

#532 fix(billing.autorenew): update payment.mean state
  client/app/account/billing/autoRenew/billing-autoRenew.html
Labels: bug

#538 fix(deps): bump ovh-api-services to v3.12.1
  yarn.lock
Labels: bug

#542 hotfix(datastores): fix order datastore action
  client/app/dedicatedCloud/datacenters/dedicatedCloud-datacenters.html
Labels: bug

#550 fix(service-expiration): display date for US
  client/app/components/expiration/service-expiration-date.component.html
Labels: bug

#552 fix(server): display subscription contacts for non US only
  client/app/dedicated/housing/dashboard/dedicated-housing-dashboard.html
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
Labels: bug

#554 fix(dedicated.server): edit display name for non-us customer
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/dedicated/server/dedicated-server.html
Labels: bug

#557 fix(service-expiration): hide link on service expiration for US
  client/app/components/expiration/service-expiration-date.component.html
Labels: bug

#559 fix(service.expiration.date): add missing $ctrl
  client/app/components/expiration/service-expiration-date.component.html
Labels: bug

#541 fix(license): fix missing ip param in agora license order
  client/app/license/order/agoraOrder/license-agoraOrder.service.js
  client/app/license/order/license-order.controller.js
  client/app/license/order/license-order.html
  client/app/license/order/license-order.service.js
Labels: bug, quality check ok

#548 fix(users): fix invalid token validator value in users table
  client/app/dedicatedCloud/user/dedicatedCloud-user.html
Labels: bug, quality check ok

#549 fix(datastores): fix host order modal overflow
  client/app/dedicatedCloud/datacenter/datastore/order/dedicatedCloud-datacenter-datastore-order.html
  client/app/dedicatedCloud/datacenter/host/order/dedicatedCloud-datacenter-host-order.html
Labels: bug, quality check ok

#566 fix(dedicatedcloud.user.passwword): disable confirm button when reseting
  client/app/dedicatedCloud/user/password/reset/dedicatedCloud-user-password-reset.controller.js
  client/app/dedicatedCloud/user/password/reset/dedicatedCloud-user-password-reset.html
Labels: bug, quality check ok

#569 fix(license order): fix missing itemId
  client/app/license/order/agoraOrder/license-agoraOrder.service.js
  client/app/license/order/options/PLESK.html
Labels: bug

#547 fix(cache-rules-loading): infinite loading
  client/app/cdn/dedicated/domain/rule/order/cdn-dedicated-domain-rule-order.html
  client/app/cdn/dedicated/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#574 fix(account.billing): billing menu inactive in EU
  client/app/components/sidebar-menu/account/sidebar-menu-account.config.js
Labels: bug

#577 fix(billing.debt): remove body request for debt payment
  client/app/account/billing/main/history/debt/pay/billing-main-history-debt-pay.controller.js
Labels: bug, quality check

#583 fix(sidebar-menu): add cloud project url to actions menu popup
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/components/sidebar-menu/translations/Messages_fr_FR.xml
  constants.config.js
Labels: bug, quality check ok

#584 chore(deps): bump ovh-angular-otrs
  yarn.lock
Labels: enhancement

#573 fix(autorenew): allow only terminate option for oneShot private database
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/billing-autoRenew.service.js
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
  client/app/account/billing/autoRenew/terminatePrivateDatabase/billing-autoRenew-terminatePrivateDatabase.controller.js
  client/app/account/billing/autoRenew/terminatePrivateDatabase/billing-autoRenew-terminatePrivateDatabase.html
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#524 feat(billing.autorenew): autoDisabled is now the same as manual
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/common/renew-helper.service.js
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#572 fix(translation): translation parameters sanitization
  client/app/app.js
Labels: bug, quality check ok

#595 fix(license agora order): set plan code for plesk powerpack option
  client/app/license/order/agoraOrder/license-agoraOrder.service.js
  client/app/license/order/license-order.controller.js
  client/app/license/order/options/PLESK.html
Labels: bug, quality check ok

#597 chore(build): Install right smarttag
  Makefile
Labels: bug

#602 fix(language): default and fallback languages
  Gruntfile.js
  client/app/app.js
  constants.config.js
Labels: bug, quality check ok

#614 fix(dedicated server): alert background color fix
  client/app/dedicated/server/bandwidth/cancel/dedicated-server-bandwidth-cancel.controller.js
  client/app/dedicated/server/bandwidth/order/dedicated-server-bandwidth-order.controller.js
  client/app/dedicated/server/dedicated-server.controller.js
  client/app/dedicated/server/dns/add/dedicated-server-dns-add.controller.js
  client/app/dedicated/server/dns/dedicated-server-dns.controller.js
  client/app/dedicated/server/dns/delete/dedicated-server-dns-delete.controller.js
  client/app/dedicated/server/firewall/disable/dedicated-server-firewall-disable.controller.js
  client/app/dedicated/server/firewall/enable/dedicated-server-firewall-enable.controller.js
  client/app/dedicated/server/firewall/order/dedicated-server-firewall-order.controller.js
  client/app/dedicated/server/firewall/rule/dedicated-server-firewall-rule.controller.js
  client/app/dedicated/server/installation/ovh/dedicated-server-installation-ovh.controller.js
  client/app/dedicated/server/ip/dedicated-server-ip-mitigation.controller.js
  client/app/dedicated/server/ip/dedicated-server-ip.controller.js
  client/app/dedicated/server/statistics/dedicated-server-statistics.controller.js
Labels: bug, quality check ok

#600 feat(billing.autorenew): SMS pack menu item redirects to renewal page
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
  client/app/account/billing/common/renew-helper.service.js
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: feature, quality check ok, translation required
