Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2018-07, with the labels that each got.

#442 chore(deps): bump ovh-ui-kit-bs to v1.2.1
  client/app/css/less/common/global.less
  package.json
  yarn.lock
Labels: bug

#446 chore(billing.autorenew): reworded sentence
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: enhancement, quality check

#443 Chore/guides links
  client/app/common/translations/Messages_fr_FR.xml
  constants.config.js
Labels: enhancement, quality check ok

#448 fix(otrs): upgrade otrs version
  yarn.lock
Labels: bug

#444 fix(billing.autorenew): display autorenew activation button again
  client/app/account/billing/autoRenew/billing-autoRenew.constants.js
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/billing-autoRenew.html
Labels: bug, quality check ok

#410 feat(sidebar): add sidebar order tracking
  client/app/components/sidebar-menu/sidebar-menu.config.js
  package.json
  yarn.lock
Labels: feature, quality check ok

#437 feat(navbar): translations for navbar placeholder
  client/app/common/translations/Messages_fr_FR.xml
  client/app/components/navbar/navbar-notification.service.js
  client/app/components/ovh-ui-angular/ovh-ui-angular.module.js
Labels: bug, quality check ok

#458 fix(*): use heading attribut on oui-back-button
  client/app/account/billing/history/balance/billing-history-balance.html
  client/app/account/billing/history/details/billing-history-details.html
  client/app/account/billing/paymentMethod/add/index.html
  client/app/account/billing/payments/request/billing-payments-request.html
  client/app/account/user/agreements/details/user-agreements-details.html
  client/app/dedicatedCloud/datacenter/datastore/orderUS/dedicatedCloud-datacenter-datastore-orderUS.html
  client/app/dedicatedCloud/datacenter/host/orderUS/dedicatedCloud-datacenter-host-orderUS.html
  client/app/ip/ip/organisation/ip-ip-organisation.html
Labels: enhancement

#461 fix(dedicated server intervention): show empty datagrid if expired
  client/app/dedicated/server/intervention/dedicated-server-intervention.controller.js
  client/app/dedicated/server/intervention/dedicated-server-intervention.html
Labels: bug

#464 fix(account): remove marketing consent optin for US
  client/app/account/user/components/newAccountForm/new-account-form-component.js
Labels: bug

#470 Fix/pcc operation
  client/app/dedicatedCloud/operation/dedicatedCloud-operation.controller.js
  client/app/dedicatedCloud/operation/dedicatedCloud-operation.html
  client/app/dedicatedCloud/operation/dedicatedCloud-operation.routes.js
  client/app/dedicatedCloud/progressBar.html
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
  package.json
  yarn.lock
Labels: enhancement, quality check ok, translation required

#469 Fix/user datagrid
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
  client/app/dedicatedCloud/user/dedicatedCloud-user.controller.js
  client/app/dedicatedCloud/user/dedicatedCloud-user.html
  client/app/dedicatedCloud/user/dedicatedCloud-user.routes.js
  client/app/dedicatedCloud/user/edit/dedicatedCloud-user-edit.controller.js
  client/app/dedicatedCloud/user/edit/dedicatedCloud-user-edit.html
  client/app/dedicatedCloud/user/edit/dedicatedCloud-user-edit.routes.js
Labels: enhancement, quality check ok, translation required

#468 fix(cache-rules-loading): infinite loading
  client/app/cdn/dedicated/domain/rule/order/cdn-dedicated-domain-rule-order.controller.js
  client/app/cdn/dedicated/domain/rule/order/cdn-dedicated-domain-rule-order.html
Labels: bug, quality check

#460 fix(license): add windows server license missing trads
  client/app/license/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#481 chore(deps): bump ovh-angular-otrs to v6.1.2
  yarn.lock
Labels: enhancement

#486 feat(billing): autorenew service in debt warning
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/warnPendingDebt/billing-autoRenew-warnPendingDebt.controller.js
  client/app/account/billing/autoRenew/warnPendingDebt/billing-autoRenew-warnPendingDebt.html
  client/app/account/billing/translations/Messages_fr_FR.xml
  client/app/common/translations/Messages_fr_FR.xml
Labels: feature, quality check

#459 fix(billing): hide useless actions for MX plan and change label
  client/app/account/billing/autoRenew/common/actions-menu-email-domain.html
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
  client/app/account/billing/common/renew-helper.service.js
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: enhancement, quality check

#487 feat(billing.mean.add): sepa fields separated for France only
  client/app/account/billing/mean/add/billing-mean-add.controller.js
  client/app/account/billing/mean/add/billing-mean-add.html
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: feature, quality check

#488 feat(billing.autorenew): add dialog before paying service while havin…
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/debtBeforePaying/billing-autoRenew-debtBeforePaying.controller.js
  client/app/account/billing/autoRenew/debtBeforePaying/billing-autoRenew-debtBeforePaying.html
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: feature, quality check ok

#477 Feat: allow undoing cancellations
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/billing-autoRenew.html
  client/app/account/billing/autoRenew/common/actions-menu.html
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
  client/app/account/billing/autoRenew/delete/billing-autoRenew-delete.controller.js
  client/app/account/billing/autoRenew/delete/billing-autoRenew-delete.html
  client/app/account/billing/autoRenew/disableAutoRenewDomains/billing-autoRenew-disableAutoRenewDomains.controller.js
  client/app/account/billing/autoRenew/disableAutoRenewDomains/billing-autoRenew-disableAutoRenewDomains.html
  client/app/account/billing/autoRenew/domain/actions-menu.html
  client/app/account/billing/autoRenew/domain/billing-autoRenew-domain.controller.js
  client/app/account/billing/autoRenew/domain/billing-autoRenew-domain.html
  client/app/account/billing/autoRenew/hosting/actions-menu.html
  client/app/account/billing/autoRenew/hosting/billing-autoRenew-hosting.html
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#479 Fix: autorenew cancellation wording & character issues
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/common/renew-helper.service.js
  client/app/account/billing/components/directives/renew/renew-date.component.js
  client/app/account/billing/components/directives/renew/renew-label.component.js
  client/app/account/billing/components/filters/renewFrequence.js
  client/app/account/billing/components/renewDate/billing-renew-date.component.js
  client/app/account/billing/components/renewDate/billing-renew-date.html
  client/app/account/billing/components/renewLabel/billing-renew-label.component.js
  client/app/account/billing/components/renewLabel/billing-renew-label.html
  client/app/account/billing/translations/Messages_fr_FR.xml
  client/app/app.js
Labels: enhancement, quality check ok

#495 fix(billing.renew): have two buttons instead of one for service paying
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
Labels: bug

#496 fix(billing.mean.add): fix adding credit card and paypal account
  client/app/account/billing/mean/add/billing-mean-add.controller.js
Labels: bug, quality check

#493 hotfix action dropdown menu does not work in mobile
  client/app/css/less/utils/variables.less
Labels: bug, quality check ok

#485 fix(*): text on edit dedicated service popup overflows out of modal
  client/app/account/billing/autoRenew/update/billing-autoRenew-update.html
Labels: bug, quality check ok

#499 fix(billing.autorenew): added back menu item
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
Labels: bug, quality check ok
