Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2018-09, with the labels that each got.

#613 Fix/change operation execution date
  client/app/common/translations/Messages_fr_FR.xml
  client/app/components/ovh-ui-angular/ovh-ui-angular.module.js
  client/app/dedicatedCloud/operation/dedicatedCloud-operation.controller.js
  client/app/dedicatedCloud/operation/dedicatedCloud-operation.html
  client/app/dedicatedCloud/operation/dedicatedCloud-operation.routes.js
  client/app/dedicatedCloud/operation/executionDateEdit/dedicatedCloud-operation-executionDateEdit.controller.js
  client/app/dedicatedCloud/operation/executionDateEdit/dedicatedCloud-operation-executionDateEdit.html
  client/app/dedicatedCloud/operation/executionDateEdit/translations/Messages_fr_FR.xml
  package.json
  yarn.lock
Labels: bug, quality check ok, translation required

#618 update minSizeWindows
  client/app/dedicated/server/installation/ovh/dedicated-server-installation-ovh.controller.js
Labels: bug, good first issue, quality check ok

#622 feat(billing.terminate): next steps confirm termination
  client/app/account/billing/confirmTerminate/billing-confirmTerminate.controller.js
  client/app/account/billing/confirmTerminate/billing-confirmTerminate.html
  client/app/account/billing/confirmTerminate/billing-confirmTerminate.service.js
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: quality check ok, translation required

#624 fix(license.detail): apply tag-pair rule on dd element
  client/app/license/detail/license-detail.html
Labels: bug

#607 feat(dedicatedcloud.datacenter.host.order): added help message
  client/app/dedicatedCloud/datacenter/host/order/dedicatedCloud-datacenter-host-order.html
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#632 fix(package): fix ui-kit versions
  package.json
  yarn.lock
Labels: bug, quality check ok

#625 fix(billing.autorenew): prevent renewal&cancellation for all
  client/app/account/billing/autoRenew/debtBeforePaying/billing-autoRenew-debtBeforePaying.controller.js
  client/app/account/billing/autoRenew/domain/billing-autoRenew-domain.html
  client/app/account/billing/autoRenew/hosting/billing-autoRenew-hosting.html
Labels: bug, quality check ok

#641 fix(us): switch ovhcloud.com to us.ovhcloud.com
  constants.config.js
  server/config/environment/index.js
Labels: bug

#639 Bugfix/invalid guide links
  client/app/account/user/ssh/user-ssh.html
  constants.config.js
Labels: bug, quality check ok

#635 Bugfix/export bills
  client/app/account/billing/main/history/billing-main-history.controller.js
Labels: bug, quality check ok

#652 feat(us): activate veeam backup
  client/app/dedicatedCloud/datacenter/backup/dedicatedCloud-datacenter-backup.controller.js
  client/app/dedicatedCloud/datacenter/backup/dedicatedCloud-datacenter-backup.html
  client/app/dedicatedCloud/datacenter/backup/enableAgora/dedicatedCloud-datacenter-backup-enableAgora.controller.js
  client/app/dedicatedCloud/datacenter/backup/enableAgora/dedicatedCloud-datacenter-backup-enableAgora.html
  client/app/dedicatedCloud/datacenter/backup/enableAgora/dedicatedCloud-datacenter-backup-enableAgora.routes.js
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
  constants.config.js
Labels: feature, quality check ok, translation required
