Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2018-10, with the labels that each got.

#662 docs(readme): fix contributing link
  CONTRIBUTING.md
Labels: bug

#663 build(webpack): add missing extras entry
  webpack.config.js
Labels: bug

#664 build(webpack): add hash to output.filename
  webpack.config.js
Labels: enhancement

#668 build(scripts.test): run yarn lint command
  package.json
Labels: bug

#671 fix(license): fix license spla add modal
  client/app/license/spla/add/licence-spla-add.routes.js
Labels: bug

#670 fix(webpack): fix broken ui-angular import
  client/app/index.js
Labels: bug

#672 fix(style): fix lint
  client/app/css/less/common/buttonIcons.less
  client/app/css/less/common/icon.less
  client/app/css/less/module/vps/vps.less
  client/app/css/less/utils/utilities.less
  client/app/css/less/utils/variables.less
Labels: bug

#674 fix(otrs): add translations
  client/app/components/ovh-angular-otrs/ovh-angular-otrs.js
Labels: bug

#676 fix(cdn): fix quota order error
  client/app/cdn/dedicated/quota/order/cdn-dedicated-quota-order.html
Labels: bug, quality check

#655 feat(billing.termination): Add new reasons
  client/app/account/billing/confirmTerminate/billing-confirmTerminate.controller.js
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: feature, quality check ok, translation required

#667 build: remove deprecated npm-scripts-config|conventional-changelog
  .scriptsrc
  package.json
  yarn.lock
Labels: enhancement

#683 fix: update gitignore file
  .gitignore
  yarn.lock
Labels: enhancement

#677 fix(summitbanner): display only for some subsidiaries
  client/app/configuration/configuration.controller.js
  client/app/configuration/configuration.html
  yarn.lock
Labels: bug, quality check

#688 fix: remove border top of the summit banner
  client/app/css/less/common/navbar.less
  yarn.lock
Labels: bug

#691 build: add clean script
  package.json
Labels: enhancement

#693 fix(components.manager-preload): center hr element
  client/app/components/manager-preload/manager-preload.less
Labels: bug

#692 build: remove duplicate dependencies
  .gitignore
  client/app/css/less/common/countryIcon.less
  client/app/css/less/common/distributionIcon.less
  client/app/css/less/common/header.less
  client/app/css/less/common/icon.less
  client/app/css/less/common/navbar.less
  client/app/css/less/dedicated/dedicatedcloud/security-options.less
  client/app/css/less/dedicated/server/usb.less
  client/app/css/less/dedicated/vrack/vrack.less
  client/app/css/less/module/ip/ip.less
  client/app/css/less/utils/utilities.less
  package.json
  yarn.lock
Labels: enhancement

#653 fix(pcc.datacenter.host): changed message and removed cross
  client/app/dedicatedCloud/datacenter/host/order/dedicatedCloud-datacenter-host-order.html
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#702 build(dedicated.cloud): translations for vm encryption kms
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: translation required

#687 fix(billing.autorenew): changed title for dialogs
  client/app/account/billing/autoRenew/debtBeforePaying/billing-autoRenew-debtBeforePaying.html
  client/app/account/billing/autoRenew/warnPendingDebt/billing-autoRenew-warnPendingDebt.html
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#678 feat: add veeam enterprise
  client/app/account/billing/autoRenew/billing-autoRenew.service.js
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: feature, quality check ok, translation required

#704 build(commitlint): remove unused config-conventional
  .commitlintrc.js
  package.json
  yarn.lock
Labels: enhancement

#706 fix(2fa): phone number preload
  client/app/account/user/security/2fa/user-security-2fa.controller.js
  client/app/account/user/security/2fa/user-security-2fa.html
  client/app/css/source.less
Labels: bug, enhancement, quality check ok

#682 feat(dedicated.cloud): add VM Encryption kms
  client/app/config/constants.config.js
  client/app/dedicatedCloud/dedicatedCloud.constant.js
  client/app/dedicatedCloud/dedicatedCloud.service.js
  client/app/dedicatedCloud/security/dedicatedCloud-security.controller.js
  client/app/dedicatedCloud/security/dedicatedCloud-security.html
  client/app/dedicatedCloud/security/dedicatedCloud-security.routes.js
  client/app/dedicatedCloud/security/kms/add/dedicatedCloud-security-kms-add.controller.js
  client/app/dedicatedCloud/security/kms/add/dedicatedCloud-security-kms-add.html
  client/app/dedicatedCloud/security/kms/delete/dedicatedCloud-security-kms-delete.controller.js
  client/app/dedicatedCloud/security/kms/delete/dedicatedCloud-security-kms-delete.html
  client/app/dedicatedCloud/security/kms/edit/dedicatedCloud-security-kms-edit.controller.js
  client/app/dedicatedCloud/security/kms/edit/dedicatedCloud-security-kms-edit.html
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: feature, quality check ok, translation required

#715 fix(dedicatedcloud.security): fix guides
  client/app/config/constants.config.js
  client/app/dedicatedCloud/security/kms/add/dedicatedCloud-security-kms-add.controller.js
Labels: bug, quality check ok

#724 Feat/summit banner : change subscription banner to live banner
  client/app/common/translations/Messages_cs_CZ.xml
  client/app/common/translations/Messages_de_DE.xml
  client/app/common/translations/Messages_en_ASIA.xml
  client/app/common/translations/Messages_en_AU.xml
  client/app/common/translations/Messages_en_CA.xml
  client/app/common/translations/Messages_en_GB.xml
  client/app/common/translations/Messages_en_SG.xml
  client/app/common/translations/Messages_en_US.xml
  client/app/common/translations/Messages_es_ES.xml
  client/app/common/translations/Messages_es_US.xml
  client/app/common/translations/Messages_fi_FI.xml
  client/app/common/translations/Messages_fr_CA.xml
  client/app/common/translations/Messages_fr_FR.xml
  client/app/common/translations/Messages_it_IT.xml
  client/app/common/translations/Messages_lt_LT.xml
  client/app/common/translations/Messages_nl_NL.xml
  client/app/common/translations/Messages_pl_PL.xml
  client/app/common/translations/Messages_pt_PT.xml
  client/app/configuration/configuration.html
  client/app/images/summit/banner-manager-2500x235-en.jpg
  client/app/images/summit/banner-manager-2500x235-fr.jpg
  client/app/images/summit/banner-manager-768x200-en.jpg
  client/app/images/summit/banner-manager-768x200-fr.jpg
Labels: quality check ok

#731 build(deps): upgrade ovh-module-exchange to v9.0.4
  client/app/index.js
  yarn.lock
Labels: enhancement

#730 refactor: remove summit banner
  client/app/common/translations/Messages_cs_CZ.xml
  client/app/common/translations/Messages_de_DE.xml
  client/app/common/translations/Messages_en_ASIA.xml
  client/app/common/translations/Messages_en_AU.xml
  client/app/common/translations/Messages_en_CA.xml
  client/app/common/translations/Messages_en_GB.xml
  client/app/common/translations/Messages_en_SG.xml
  client/app/common/translations/Messages_en_US.xml
  client/app/common/translations/Messages_es_ES.xml
  client/app/common/translations/Messages_es_US.xml
  client/app/common/translations/Messages_fi_FI.xml
  client/app/common/translations/Messages_fr_CA.xml
  client/app/common/translations/Messages_fr_FR.xml
  client/app/common/translations/Messages_it_IT.xml
  client/app/common/translations/Messages_lt_LT.xml
  client/app/common/translations/Messages_nl_NL.xml
  client/app/common/translations/Messages_pl_PL.xml
  client/app/common/translations/Messages_pt_PT.xml
  client/app/configuration/configuration.controller.js
  client/app/configuration/configuration.html
  client/app/images/summit/banner-manager-2500x235-en.jpg
  client/app/images/summit/banner-manager-2500x235-fr.jpg
  client/app/images/summit/banner-manager-768x200-en.jpg
  client/app/images/summit/banner-manager-768x200-fr.jpg
Labels: enhancement, quality check ok

#740 build(scripts): add clean dist script
  package.json
Labels: enhancement

#738 refactor(eslint): switch to json format as configuration file
  .eslintrc.json
Labels: enhancement

#739 refactor: extract configuration from package.json into json files
  .huskyrc.json
  .lintstagedrc.json
  package.json
Labels: enhancement

#741 build(deps): upgrade manager-webpack-config to v2.3.4
  yarn.lock
Labels: enhancement

#723 fix(pcc): us veeam link
  client/app/config/constants.config.js
  client/app/dedicatedCloud/datacenter/backup/enableAgora/dedicatedCloud-datacenter-backup-enableAgora.controller.js
Labels: bug, quality check ok

#745 Bump manager webpack config
  README.md
  yarn.lock
Labels: enhancement

#748 Sort package json
  package.json
Labels: enhancement

#744 fix(dedicated.installation): fix progress for expired servers
  client/app/dedicated/server/dedicated-server.controller.js
Labels: bug, quality check ok

#754 build(webpack): set correct entry list
  webpack.config.js
Labels: :jack_o_lantern: one-manager

#755 refactor: use @ovh-ux/translate-async-loader
  client/app/app.js
  client/app/async-loader.factory.js
  package.json
  yarn.lock
Labels: :jack_o_lantern: one-manager

#757 build(deps): upgrade manager-webpack-config to v2.4.0
  package.json
  yarn.lock
Labels: :jack_o_lantern: one-manager
