Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2019-02, with the labels that each got.

#952 build(deps): upgrade ng-ovh-sso-auth and ng-ovh-sso-auth-modal-plugin
  client/app/app.js
  client/app/components/ovh-angular-sso-auth/ovh-angular-sso-auth.module.js
  client/app/css/source.less
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, quality check ok

#959 fix(dedicated.ftpbackup): add limit to ip blocks
  client/app/dedicated/server/ftp-backup/access/add/dedicated-server-ftp-backup-access-add.controller.js
  client/app/dedicated/server/ftp-backup/access/add/dedicated-server-ftp-backup-access-add.html
  client/app/dedicated/server/ftp-backup/dedicated-server-ftp-backup.constants.js
  client/app/dedicated/server/ftp-backup/dedicated-server-ftp-backup.html
  client/app/dedicated/server/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#962 fix(deps): upgrade exchange module
  package.json
  yarn.lock
Labels: bug

#963 fix(i18n): extract translations
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: bug

#965 fix(deps): upgrade exchange module
  package.json
  yarn.lock
Labels: bug

#968 fix(ip.statistics): display correct units and details
  client/app/ip/ip/mitigation/statistics/ip-ip-mitigation-statistics.controller.js
Labels: bug, quality check ok

#951 fix(billing.payment): add explain text for credit card add
  client/app/account/billing/payment/method/add/billing-payment-method-add.constants.js
  client/app/account/billing/payment/method/add/billing-payment-method-add.controller.js
  client/app/account/billing/payment/method/add/billing-payment-method-add.html
  client/app/account/billing/payment/method/add/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#977 fix(deps): upgrade ng-ovh-apiv7 to v2.0.0
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#979 fix(billing.balance): call to existing method
  client/app/account/billing/main/history/balance/billing-history-balance.controller.js
Labels: bug, quality check ok

#983 fix(i18n): retrieve translations
  client/app/account/billing/payment/method/add/views/billing-address/translations/Messages_es_ES.xml
  client/app/account/billing/translations/Messages_en_US.xml
  client/app/account/billing/translations/Messages_es_ES.xml
  client/app/account/billing/translations/Messages_it_IT.xml
  client/app/account/billing/translations/Messages_pt_PT.xml
  client/app/account/user/translations/Messages_es_ES.xml
  client/app/dedicated/housing/translations/Messages_de_DE.xml
  client/app/dedicated/housing/translations/Messages_es_ES.xml
  client/app/dedicated/housing/translations/Messages_it_IT.xml
  client/app/dedicated/nas/translations/Messages_es_ES.xml
  client/app/dedicated/server/display-name/translations/Messages_es_ES.xml
  client/app/dedicated/server/translations/Messages_de_DE.xml
  client/app/dedicated/server/translations/Messages_es_ES.xml
  client/app/dedicated/server/translations/Messages_it_IT.xml
  client/app/dedicated/server/translations/Messages_pl_PL.xml
  client/app/dedicated/server/translations/Messages_pt_PT.xml
  client/app/dedicatedCloud/translations/Messages_de_DE.xml
  client/app/dedicatedCloud/translations/Messages_es_ES.xml
  client/app/dedicatedCloud/translations/Messages_it_IT.xml
  client/app/dedicatedCloud/translations/Messages_pl_PL.xml
  client/app/dedicatedCloud/translations/Messages_pt_PT.xml
Labels: bug

#985 refactor: remove legacies payment services and use ng-ovh-payment-method
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/mean/billing-mean.service.js
  client/app/account/billing/payment/ovhAccount/retrieve/billing-ovhAccount-retrieve.controller.js
  client/app/account/billing/payment/ovhAccount/retrieve/billing-ovhAccount-retrieve.html
  client/app/account/billing/paymentInformation/billing-paymentInformation.service.js
  client/app/account/billing/paymentMethod/billing-paymentMethod.service.js
Labels: enhancement, quality check ok

#978 Fix/dedicated expired tasks
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/dedicated/server/dashboard/dedicated-server-dashboard.routes.js
  client/app/dedicated/server/dedicated-server-tabs.controller.js
  client/app/dedicated/server/dedicated-server.controller.js
  client/app/dedicated/server/dedicated-server.html
  client/app/dedicated/server/dedicated-server.routes.js
  client/app/dedicated/server/display-name/display-name.routes.js
  client/app/dedicated/server/dns/dedicated-server-dns.routes.js
  client/app/dedicated/server/firewall/dedicated-server-firewall.routes.js
  client/app/dedicated/server/ftp-backup/dedicated-server-ftp-backup.routes.js
  client/app/dedicated/server/intervention/dedicated-server-intervention.routes.js
  client/app/dedicated/server/ipmi/dedicated-server-ipmi.routes.js
  client/app/dedicated/server/monitoring/update/dedicated-server-monitoring-update.routes.js
  client/app/dedicated/server/ovh-tasks/dedicated-server-ovh-tasks.routes.js
  client/app/dedicated/server/reboot/dedicated-server-reboot.routes.js
  client/app/dedicated/server/statistics/dedicated-server-statistics.controller.js
  client/app/dedicated/server/task/dedicated-server-task.html
  client/app/dedicated/server/task/dedicated-server-task.routes.js
  client/app/dedicated/server/usb-storage/dedicated-server-usb-storage.routes.js
Labels: bug, enhancement, quality check ok
