Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2019-07, with the labels that each got.

#1212 Fix/rtm bug fixes
  client/app/config/constants.config.js
  client/app/dedicated/server/statistics/infos.html
  client/app/dedicated/server/statistics/rtm/load-avg/dedicated-server-statistics-rtm-load-avg.controller.js
  client/app/dedicated/server/statistics/rtm/load-avg/dedicated-server-statistics-rtm-load-avg.html
Labels: bug, quality check ok

#1220 Release v10.19.2
  client/app/config/constants.config.js
  client/app/dedicated/server/statistics/infos.html
  client/app/dedicated/server/statistics/rtm/load-avg/dedicated-server-statistics-rtm-load-avg.controller.js
  client/app/dedicated/server/statistics/rtm/load-avg/dedicated-server-statistics-rtm-load-avg.html
  package.json
  yarn.lock
Labels: release :package:

#1223 fix(drp): return correct object of plan state response
  client/app/dedicatedCloud/datacenter/drp/dedicatedCloud-datacenter-drp.service.js
Labels: bug, quality check ok

#1228 fix: get access to the chatbot from both billing and account section
  client/app/index.html
Labels: bug, quality check ok

#1229 build(deps): upgrade ovh-api-services to v7.0.0
  package.json
  yarn.lock
Labels: dependencies

#1227 fix(trans-fix): fix translations
  client/app/account/billing/payment/transactions/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required

#1234 build(deps): upgrade ng-ovh-otrs to v7.1.6
  package.json
  yarn.lock
Labels: bug, dependencies

#1233 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1232 Release v10.19.5
  client/app/account/billing/payment/transactions/translations/Messages_fr_FR.json
  client/app/license/translations/Messages_de_DE.json
  client/app/license/translations/Messages_en_ASIA.json
  client/app/license/translations/Messages_en_AU.json
  client/app/license/translations/Messages_en_CA.json
  client/app/license/translations/Messages_en_GB.json
  client/app/license/translations/Messages_en_SG.json
  client/app/license/translations/Messages_en_US.json
  client/app/license/translations/Messages_es_ES.json
  client/app/license/translations/Messages_fi_FI.json
  client/app/license/translations/Messages_it_IT.json
  client/app/license/translations/Messages_lt_LT.json
  client/app/license/translations/Messages_pl_PL.json
  client/app/license/translations/Messages_pt_PT.json
  package.json
  yarn.lock
Labels: release :package:

#1241 fix(user-contracts): non breaking space in ng-bind
  client/app/user-contracts/modal/user-contracts-accept.html
Labels: bug

#1250 build: add __NG_APP_INJECTIONS__ to facilitate module injection
  .eslintrc.json
  client/app/app.js
  webpack.config.js
Labels: build

#1249 refactor: replace component with ng-uirouter-layout
  client/app/app.js
  client/app/components/angular-ui-router/angular-ui-router.module.js
  client/app/dedicatedCloud/resource/upgrade/upgrade.state.js
  package.json
  yarn.lock
Labels: dependencies, quality check ok

#1257 Release v10.19.8
  client/app/account/billing/payment/transactions/translations/Messages_de_DE.json
  client/app/account/billing/payment/transactions/translations/Messages_en_ASIA.json
  client/app/account/billing/payment/transactions/translations/Messages_en_AU.json
  client/app/account/billing/payment/transactions/translations/Messages_en_CA.json
  client/app/account/billing/payment/transactions/translations/Messages_en_GB.json
  client/app/account/billing/payment/transactions/translations/Messages_en_SG.json
  client/app/account/billing/payment/transactions/translations/Messages_en_US.json
  client/app/account/billing/payment/transactions/translations/Messages_es_ES.json
  client/app/account/billing/payment/transactions/translations/Messages_fi_FI.json
  client/app/account/billing/payment/transactions/translations/Messages_it_IT.json
  client/app/account/billing/payment/transactions/translations/Messages_lt_LT.json
  client/app/account/billing/payment/transactions/translations/Messages_pt_PT.json
  client/app/app.js
  client/app/components/angular-ui-router/angular-ui-router.module.js
  client/app/dedicatedCloud/resource/upgrade/upgrade.state.js
  client/app/ip/ip.app.js
  client/app/ip/ip/ip-ip.controller.js
  client/app/ip/ip/reverse/add/ip-ip-reverse-add.controller.js
  client/app/ip/ip/reverse/constants.js
  client/app/ip/ip/reverse/ip-ip-reverse.controller.js
  client/app/ip/ip/reverse/ip-ip-reverse.service.js
  client/app/ip/ip/reverse/update/ip-ip-reverse-update.controller.js
  client/app/ip/ip/reverse/update/ip-ip-reverse-update.html
  client/app/ip/ip/reverse/update/translations/Messages_fr_FR.json
  client/app/ip/ip/reverse/update/update.controller.js
  client/app/ip/translations/Messages_fr_FR.json
  client/app/license/translations/Messages_nl_NL.json
  package.json
  yarn.lock
Labels: release :package:

#1268 build(deps): upgrade ovh-api-services to v8.0.0
  package.json
  yarn.lock
Labels: dependencies

#1269 build(deps): upgrade ng-ovh-http to v4.0.2
  package.json
  yarn.lock
Labels: dependencies

#1260 build: remove duplicate bower dependencies
  client/app/index.js
  package.json
  yarn.lock
Labels: build, dependencies

#1263 fix(ip): allow only reverse update in ipv6 modal
  client/app/ip/ip/reverse/add/ip-ip-reverse-add.controller.js
  client/app/ip/ip/reverse/add/ip-ip-reverse-add.html
  client/app/ip/translations/Messages_fr_FR.json
Labels: quality check ok, translation required

#1272 Release v10.20.1
  client/app/dedicated/server/translations/Messages_de_DE.json
  client/app/dedicated/server/translations/Messages_en_ASIA.json
  client/app/dedicated/server/translations/Messages_en_AU.json
  client/app/dedicated/server/translations/Messages_en_CA.json
  client/app/dedicated/server/translations/Messages_en_GB.json
  client/app/dedicated/server/translations/Messages_en_SG.json
  client/app/dedicated/server/translations/Messages_en_US.json
  client/app/dedicated/server/translations/Messages_fi_FI.json
  client/app/dedicated/server/translations/Messages_it_IT.json
  client/app/dedicated/server/translations/Messages_lt_LT.json
  client/app/dedicated/server/translations/Messages_nl_NL.json
  client/app/dedicated/server/translations/Messages_pt_PT.json
  client/app/index.js
  client/app/ip/ip/reverse/add/ip-ip-reverse-add.controller.js
  client/app/ip/ip/reverse/add/ip-ip-reverse-add.html
  client/app/ip/ip/reverse/update/translations/Messages_de_DE.json
  client/app/ip/ip/reverse/update/translations/Messages_it_IT.json
  client/app/ip/ip/reverse/update/translations/Messages_pl_PL.json
  client/app/ip/ip/reverse/update/translations/Messages_pt_PT.json
  client/app/ip/translations/Messages_de_DE.json
  client/app/ip/translations/Messages_es_ES.json
  client/app/ip/translations/Messages_fr_FR.json
  client/app/ip/translations/Messages_it_IT.json
  package.json
  yarn.lock
Labels: release :package:

#1267 feat(billing.autorenew): add bulk action pages
  client/app/billing/autoRenew/BillingService.class.js
  client/app/billing/autoRenew/actions/update/update.routing.js
  client/app/billing/autoRenew/autorenew.module.js
  client/app/billing/autoRenew/autorenew.routing.js
  client/app/billing/autoRenew/billing-autoRenew.service.js
  client/app/billing/autoRenew/bulk/bulk.component.js
  client/app/billing/autoRenew/bulk/bulk.controller.js
  client/app/billing/autoRenew/bulk/bulk.html
  client/app/billing/autoRenew/bulk/bulk.module.js
  client/app/billing/autoRenew/bulk/translations/Messages_fr_FR.json
  client/app/billing/autoRenew/disable/billing-autoRenew-disable.html
  client/app/billing/autoRenew/disable/disable.component.js
  client/app/billing/autoRenew/disable/disable.controller.js
  client/app/billing/autoRenew/disable/disable.html
  client/app/billing/autoRenew/disable/disable.module.js
  client/app/billing/autoRenew/disable/disable.routing.js
  client/app/billing/autoRenew/disable/disable.service.js
  client/app/billing/autoRenew/disable/translations/Messages_fr_FR.json
  client/app/billing/autoRenew/enable/enable.component.js
  client/app/billing/autoRenew/enable/enable.controller.js
  client/app/billing/autoRenew/enable/enable.html
  client/app/billing/autoRenew/enable/enable.module.js
  client/app/billing/autoRenew/enable/enable.routing.js
  client/app/billing/autoRenew/enable/enable.service.js
  client/app/billing/autoRenew/enable/translations/Messages_fr_FR.json
Labels: feature

#1277 fix(ip.reverse.add): display error fields when value are invalid
  client/app/ip/ip/reverse/add/ip-ip-reverse-add.html
  client/app/ip/translations/Messages_fr_FR.json
Labels: quality check ok

#1276 build(deps): upgrade ng-ovh-web-universe-components to v4.0.3
  package.json
  yarn.lock
Labels: dependencies

#1245 fix(prices fix): fix prices for asia and sg region
  client/app/dedicatedUniverseComponents/price/price.filter.js
  client/app/dedicatedUniverseComponents/price/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required
