Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2019-05, with the labels that each got.

#1098 fix(i18n): retrieve translations
  client/app/account/user/newAccountForm/translations/Messages_cs_CZ.xml
  client/app/account/user/newAccountForm/translations/Messages_de_DE.xml
  client/app/account/user/newAccountForm/translations/Messages_en_ASIA.xml
  client/app/account/user/newAccountForm/translations/Messages_en_AU.xml
  client/app/account/user/newAccountForm/translations/Messages_en_CA.xml
  client/app/account/user/newAccountForm/translations/Messages_en_GB.xml
  client/app/account/user/newAccountForm/translations/Messages_en_SG.xml
  client/app/account/user/newAccountForm/translations/Messages_en_US.xml
  client/app/account/user/newAccountForm/translations/Messages_es_ES.xml
  client/app/account/user/newAccountForm/translations/Messages_es_US.xml
  client/app/account/user/newAccountForm/translations/Messages_fi_FI.xml
  client/app/account/user/newAccountForm/translations/Messages_fr_CA.xml
  client/app/account/user/newAccountForm/translations/Messages_it_IT.xml
  client/app/account/user/newAccountForm/translations/Messages_lt_LT.xml
  client/app/account/user/newAccountForm/translations/Messages_nl_NL.xml
  client/app/account/user/newAccountForm/translations/Messages_pl_PL.xml
  client/app/account/user/newAccountForm/translations/Messages_pt_PT.xml
Labels: bug

#1086 Fix/dedicated server location
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/dedicated/server/location/dedicated-server-location.html
  client/app/dedicated/server/statistics/infos.html
  client/app/dedicated/server/statistics/rtm/dedicated-server-statistics-rtm.html
  client/app/dedicated/server/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#1103 fix(deps): upgrade ovh-module-exchange to v9.4.3
  package.json
  yarn.lock
Labels: bug

#1106 fix(license): add both windows server 2019 standard and datacenter
  client/app/license/translations/Messages_fr_FR.xml
Labels: bug

#1112 fix(i18n): retrieve translations
  client/app/account/billing/main/history/debt/pay/translations/Messages_nl_NL.xml
  client/app/account/billing/payment/transactions/translations/Messages_nl_NL.xml
  client/app/account/user/newAccountForm/translations/Messages_en_ASIA.xml
  client/app/account/user/newAccountForm/translations/Messages_en_AU.xml
  client/app/account/user/newAccountForm/translations/Messages_en_CA.xml
  client/app/account/user/newAccountForm/translations/Messages_en_GB.xml
  client/app/account/user/newAccountForm/translations/Messages_en_SG.xml
  client/app/account/user/newAccountForm/translations/Messages_en_US.xml
  client/app/common/translations/Messages_nl_NL.xml
  client/app/components/sidebar-menu/translations/Messages_nl_NL.xml
  client/app/dedicated/server/translations/Messages_nl_NL.xml
  client/app/dedicated/server/translations/Messages_pl_PL.xml
  client/app/ip/translations/Messages_nl_NL.xml
  client/app/license/translations/Messages_es_ES.xml
  client/app/license/translations/Messages_it_IT.xml
Labels: bug

#1116 fix(license): add missing translations
  client/app/license/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#1118 Release v10.17.4
  client/app/license/translations/Messages_cs_CZ.xml
  client/app/license/translations/Messages_de_DE.xml
  client/app/license/translations/Messages_en_ASIA.xml
  client/app/license/translations/Messages_en_AU.xml
  client/app/license/translations/Messages_en_CA.xml
  client/app/license/translations/Messages_en_GB.xml
  client/app/license/translations/Messages_en_SG.xml
  client/app/license/translations/Messages_en_US.xml
  client/app/license/translations/Messages_es_ES.xml
  client/app/license/translations/Messages_es_US.xml
  client/app/license/translations/Messages_fi_FI.xml
  client/app/license/translations/Messages_fr_CA.xml
  client/app/license/translations/Messages_fr_FR.xml
  client/app/license/translations/Messages_it_IT.xml
  client/app/license/translations/Messages_lt_LT.xml
  client/app/license/translations/Messages_nl_NL.xml
  client/app/license/translations/Messages_pl_PL.xml
  client/app/license/translations/Messages_pt_PT.xml
Labels: bug

#1121 fix(i18n): retrieve translations
  client/app/account/user/newAccountForm/translations/Messages_de_DE.xml
  client/app/license/translations/Messages_es_ES.xml
  client/app/license/translations/Messages_it_IT.xml
Labels: bug

#1122 feat: use server-sidebar
  client/app/app.js
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/components/user/session/user-session.controller.js
  client/app/components/user/session/user-session.service.js
  client/app/index.html
  client/app/index.js
  package.json
  yarn.lock
Labels: feature

#1134 fix(deps): upgrade both core and navbar dependencies
  package.json
  yarn.lock
Labels: bug

#1137 fix(deps): upgrade manager-server-sidebar to v0.1.3
  client/app/components/product/product.service.js
  package.json
  yarn.lock
Labels: bug

#1132 fix(account.billing): add missing translation on cancellation form
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: bug, translation required

#1108 Fix/remove usb storage tab
  client/app/dedicated/server/dedicated-server.controller.js
  client/app/dedicated/server/dedicated-server.html
  client/app/dedicated/server/usb-storage/dedicated-server-usb-storage.controller.js
  client/app/dedicated/server/usb-storage/dedicated-server-usb-storage.html
Labels: bug, quality check ok

#1090 fix(usage): RTM usage chart
  client/app/cdn/dedicated/domain/statistics/cdn-dedicated-domain-statistics.controller.js
  client/app/cdn/dedicated/domain/statistics/cdn-dedicated-domain-statistics.html
  client/app/cdn/dedicated/manage/statistics/cdn-dedicated-manage-statistics.controller.js
  client/app/cdn/dedicated/manage/statistics/cdn-dedicated-manage-statistics.html
  client/app/cdn/dedicated/translations/Messages_fr_FR.xml
  client/app/dedicated/server/statistics/rtm/ServerStatsRtmGeneralController.js
  client/app/dedicated/server/statistics/rtm/load-avg/dedicated-server-statistics-rtm-load-avg.controller.js
  client/app/dedicated/server/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#1145 fix(i18n): retrieve translations
  client/app/account/user/newAccountForm/translations/Messages_en_ASIA.xml
  client/app/account/user/newAccountForm/translations/Messages_en_AU.xml
  client/app/account/user/newAccountForm/translations/Messages_en_CA.xml
  client/app/account/user/newAccountForm/translations/Messages_en_GB.xml
  client/app/account/user/newAccountForm/translations/Messages_en_SG.xml
  client/app/account/user/newAccountForm/translations/Messages_en_US.xml
  client/app/account/user/newAccountForm/translations/Messages_fr_CA.xml
  client/app/account/user/translations/Messages_en_ASIA.xml
  client/app/account/user/translations/Messages_en_AU.xml
  client/app/account/user/translations/Messages_en_CA.xml
  client/app/account/user/translations/Messages_en_GB.xml
  client/app/account/user/translations/Messages_en_SG.xml
  client/app/account/user/translations/Messages_en_US.xml
  client/app/account/user/translations/Messages_fr_CA.xml
  client/app/account/user/translations/Messages_pt_PT.xml
  client/app/cdn/dedicated/translations/Messages_de_DE.xml
  client/app/cdn/dedicated/translations/Messages_it_IT.xml
  client/app/cdn/dedicated/translations/Messages_pt_PT.xml
  client/app/components/sidebar-menu/account/translations/Messages_pt_PT.xml
  client/app/dedicated/server/translations/Messages_de_DE.xml
  client/app/dedicated/server/translations/Messages_it_IT.xml
  client/app/dedicated/server/translations/Messages_pt_PT.xml
Labels: bug

#1155 fix(deps): upgrade ovh-module-exchange to v9.4.5
  package.json
  yarn.lock
Labels: bug

#1157 fix(deps): upgrade manager-server-sidebar to 0.1.6
  package.json
  yarn.lock
Labels: bug
