Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2019-10, with the labels that each got.

#1417 fix(billing.autorenew): add option to align renew dates
  client/app/billing/autoRenew/autorenew.constants.js
  client/app/billing/autoRenew/autorenew.controller.js
  client/app/billing/autoRenew/autorenew.html
  client/app/billing/autoRenew/autorenew.routing.js
  client/app/billing/autoRenew/translations/Messages_fr_FR.json
  client/app/config/constants.config.js
Labels: bug, quality check ok, translation required

#1425 fix(error-page): reload to go to home page
  client/app/error/error.routing.js
Labels: bug

#1426 fix(billing.autorenew): allow immediate service termination
  client/app/billing/autoRenew/actions/terminate/terminate.controller.js
  client/app/billing/autoRenew/actions/terminateEmail/billing-autoRenew-terminateEmail.controller.js
  client/app/billing/autoRenew/actions/terminateHostingWeb/billing-autoRenew-terminateHostingWeb.controller.js
  client/app/billing/autoRenew/actions/terminatePrivateDatabase/billing-autoRenew-terminatePrivateDatabase.controller.js
  client/app/billing/autoRenew/actions/terminatePrivateDatabase/billing-autoRenew-terminatePrivateDatabase.html
  client/app/billing/autoRenew/autorenew.html
  client/app/billing/autoRenew/autorenew.routing.js
Labels: bug

#1428 trans(ola): translations for OLA
  client/app/dedicated/housing/translations/Messages_fr_FR.json
  client/app/dedicated/server/interfaces/ola-activation/translations/Messages_fr_FR.json
  client/app/dedicated/server/interfaces/ola-configuration/translations/Messages_fr_FR.json
  client/app/dedicated/server/interfaces/ola-terminate/translations/Messages_fr_FR.json
  client/app/dedicated/server/interfaces/translations/Messages_fr_FR.json
  client/app/dedicated/server/translations/Messages_fr_FR.json
Labels: bug, translation required

#1430 feat(dedicated-server): extract translations
  client/app/dedicated/server/bandwidth/dashboard/translations/Messages_fr_FR.json
  client/app/dedicated/server/interfaces/ola-configuration/translations/Messages_fr_FR.json
  client/app/dedicated/server/interfaces/translations/Messages_fr_FR.json
Labels: feature

#1433 Fix/ola issues
  client/app/dedicated/server/bandwidth/private-order/private-order.html
  client/app/dedicated/server/bandwidth/public-order/public-order.html
  client/app/dedicated/server/interfaces/interfaces.html
  client/app/dedicated/server/interfaces/ola-configuration/ola-configuration.html
  client/app/dedicated/server/interfaces/ola-configuration/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required

#1431 feat: enterprise cloud database
  client/app/app.js
  client/app/billing/autoRenew/actions/terminate-enterprise-cloud-database/terminate-enterprise-cloud-database.component.js
  client/app/billing/autoRenew/actions/terminate-enterprise-cloud-database/terminate-enterprise-cloud-database.controller.js
  client/app/billing/autoRenew/actions/terminate-enterprise-cloud-database/terminate-enterprise-cloud-database.html
  client/app/billing/autoRenew/actions/terminate-enterprise-cloud-database/terminate-enterprise-cloud-database.module.js
  client/app/billing/autoRenew/actions/terminate-enterprise-cloud-database/terminate-enterprise-cloud-database.routing.js
  client/app/billing/autoRenew/actions/terminate-enterprise-cloud-database/translations/Messages_en_GB.json
  client/app/billing/autoRenew/actions/terminate-enterprise-cloud-database/translations/Messages_fr_FR.json
  client/app/billing/autoRenew/autorenew.component.js
  client/app/billing/autoRenew/autorenew.html
  client/app/billing/autoRenew/autorenew.module.js
  client/app/billing/autoRenew/autorenew.routing.js
  client/app/billing/autoRenew/translations/Messages_en_GB.json
  client/app/billing/autoRenew/translations/Messages_fr_FR.json
  package.json
  webpack.config.js
  yarn.lock
Labels: feature, quality check, translation required

#1434 fix(dedicated-server): catch errors and improve loading
  client/app/dedicated/server/interfaces/interfaces.constants.js
  client/app/dedicated/server/interfaces/interfaces.controller.js
  client/app/dedicated/server/interfaces/interfaces.service.js
  client/app/dedicated/server/interfaces/ola-configuration/ola-configuration.controller.js
  client/app/dedicated/server/interfaces/ola-configuration/ola-configuration.html
  client/app/dedicated/server/interfaces/ola-configuration/ola-configuration.routing.js
  client/app/dedicated/server/interfaces/ola-configuration/translations/Messages_fr_FR.json
  client/app/dedicated/server/interfaces/translations/Messages_fr_FR.json
Labels: bug

#1432 Fix/activate autorenew
  client/app/billing/autoRenew/actions/activation/activation.routing.js
  client/app/billing/autoRenew/autorenew.constants.js
  client/app/billing/autoRenew/autorenew.service.js
Labels: bug

#1442 fix: server sidebar version update
  client/app/billing/autoRenew/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: bug, dependencies, translation required

#1445 fix(account.contacts.service): post to the right URL
  client/app/account/contacts/service/contacts-service.service.js
Labels: bug

#1446 fix(account.user): set the right base url for setAction
  client/app/account/user/user.controller.js
Labels: bug

#1448 fix(deps): upgrade ovh-module-exchange to v9.4.9
  package.json
  yarn.lock
Labels: bug, dependencies

#1451 fix(account.contacts): add setAction for contacts change
  client/app/account/contacts/update/user.contacts-update.routes.js
  client/app/account/contacts/user-contacts.controller.js
  client/app/account/contacts/user-contacts.html
Labels: bug

#1454 fix(billing.autorenew.ssh): rename broken service name
  client/app/billing/autoRenew/ssh/user-ssh.service.js
Labels: bug

#1461 fix(account.user.support.level): use right URLs in constant file
  client/app/account/user/support-level/support-level.constants.js
Labels: bug

#1415 fix(billing.autorenew): set page offset for current page
  client/app/billing/autoRenew/autorenew.component.js
  client/app/billing/autoRenew/autorenew.controller.js
  client/app/billing/autoRenew/autorenew.routing.js
Labels: bug, quality check ok

#1460 fix: fix spelling mistakes
  client/app/dedicated/nas/translations/Messages_fr_FR.json
  client/app/dedicated/server/translations/Messages_fr_FR.json
Labels: enhancement

#1416 feat(billing.autorenew): update wording for expiration date
  client/app/billing/autoRenew/autorenew.controller.js
  client/app/billing/autoRenew/autorenew.html
  client/app/billing/autoRenew/translations/Messages_fr_FR.json
Labels: feature, quality check ok, translation required

#1464 feat(autorenew): add webcoach
  client/app/billing/autoRenew/actions/terminate-webcoach/terminate-webcoach.component.js
  client/app/billing/autoRenew/actions/terminate-webcoach/terminate-webcoach.controller.js
  client/app/billing/autoRenew/actions/terminate-webcoach/terminate-webcoach.html
  client/app/billing/autoRenew/actions/terminate-webcoach/terminate-webcoach.module.js
  client/app/billing/autoRenew/actions/terminate-webcoach/terminate-webcoach.routing.js
  client/app/billing/autoRenew/actions/terminate-webcoach/translations/Messages_fr_FR.json
  client/app/billing/autoRenew/autorenew.component.js
  client/app/billing/autoRenew/autorenew.html
  client/app/billing/autoRenew/autorenew.module.js
  client/app/billing/autoRenew/autorenew.routing.js
  client/app/billing/autoRenew/translations/Messages_fr_FR.json
  client/app/billing/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: dependencies, feature

#1465 fix(account.user.advanced): restore the activation button
  client/app/account/user/advanced/advanced.routing.js
Labels: bug

#1467 fix(account.contacts): filter service on category
  client/app/account/contacts/service/edit/edit.routing.js
  client/app/account/contacts/service/user-contacts-service.routes.js
Labels: bug

#1472 fix(billing.autorenew.ssh): scope function binding
  client/app/billing/autoRenew/ssh/user-ssh.controller.js
Labels: bug

#1478 fix(pcc.drp): handle unavailable pccs
  client/app/dedicatedCloud/dedicatedCloud.constant.js
  client/app/dedicatedCloud/dedicatedCloud.service.js
Labels: bug, quality check ok

#1475 fix(account.contact): display feedback message
  client/app/account/contacts/service/user-contacts-service.html
  client/app/account/contacts/service/user-contacts-service.routes.js
Labels: bug

#1473 fix(ssh): still display sshkeys if one is in error
  client/app/billing/autoRenew/ssh/user-ssh.controller.js
  client/app/billing/autoRenew/ssh/user-ssh.service.js
Labels: bug, quality check ok

#1483 fix: fix redirection of contact
  client/app/account/contacts/service/contacts-service.component.js
  client/app/account/contacts/service/edit/edit.routing.js
  client/app/account/contacts/service/user-contacts-service.controller.js
  client/app/account/contacts/service/user-contacts-service.html
  client/app/account/contacts/service/user-contacts-service.routes.js
  package.json
  yarn.lock
Labels: bug, quality check ok

#1491 fix(sidebar.menu): uses ngTranslationsInject to load translations
  client/app/components/sidebar-menu/account/sidebar-menu-account.config.js
  client/app/components/sidebar-menu/sidebar-menu.js
Labels: bug

#1485 fix(licence): translation issue in plesk licence
  client/app/license/order/options/PLESK.html
  client/app/license/translations/Messages_fr_FR.json
Labels: bug, quality check ok

#1495 fix: retractation translations path
  client/app/billing/orders/retraction/retraction.routing.js
Labels: bug

#1494 fix(dedicated.server): activate public bandwidth order
  client/app/dedicated/server/bandwidth/dashboard/dashboard.html
  client/app/dedicated/server/dedicated-server.service.js
  client/app/dedicated/server/translations/Messages_en_GB.json
  client/app/dedicated/server/translations/Messages_fr_FR.json
Labels: bug, quality check ok

#1391 feat(billing.autorenew): improve message when no service is excluded
  client/app/billing/autoRenew/bulk/bulk.component.js
  client/app/billing/autoRenew/bulk/bulk.html
  client/app/billing/autoRenew/bulk/translations/Messages_fr_FR.json
  client/app/billing/autoRenew/disable/disable.controller.js
  client/app/billing/autoRenew/disable/disable.html
  client/app/billing/autoRenew/disable/translations/Messages_fr_FR.json
  client/app/billing/autoRenew/enable/enable.controller.js
  client/app/billing/autoRenew/enable/enable.html
  client/app/billing/autoRenew/enable/enable.module.js
  client/app/billing/autoRenew/enable/translations/Messages_fr_FR.json
  client/app/models/BillingService.class.js
Labels: feature, quality check ok, translation required

#1410 feat(billing.autorenew.bulk): display eligible services
  client/app/billing/autoRenew/bulk/bulk.html
  client/app/billing/autoRenew/bulk/translations/Messages_fr_FR.json
Labels: feature, quality check ok, translation required

#1507 fix(deps): upgrade manager-server-sidebar to v0.6.7
  package.json
  yarn.lock
Labels: bug, quality check ok

#1514 fix(i18n): add missing translations [CDS 92]
  client/app/billing/autoRenew/bulk/translations/Messages_de_DE.json
  client/app/billing/autoRenew/disable/translations/Messages_de_DE.json
  client/app/billing/autoRenew/enable/translations/Messages_de_DE.json
  client/app/billing/autoRenew/translations/Messages_en_GB.json
  client/app/billing/autoRenew/translations/Messages_fi_FI.json
  client/app/billing/autoRenew/translations/Messages_lt_LT.json
  client/app/billing/payment/method/translations/Messages_de_DE.json
  client/app/dedicated/server/translations/Messages_de_DE.json
Labels: bug

#1505 fix(dedicated-servers): fix servers list sorting issue
  client/app/dedicated/server/servers/servers.controller.js
  client/app/dedicated/server/servers/servers.html
Labels: bug, quality check ok

#1484 fix(licences): fix purchase order button
  client/app/license/order/license-order.html
Labels: bug, quality check ok

#1519 Release v10.33.3
  client/app/mfaEnrollment/translations/Messages_en_GB.json
  client/app/mfaEnrollment/translations/Messages_fi_FI.json
  client/app/mfaEnrollment/translations/Messages_fr_CA.json
  client/app/mfaEnrollment/translations/Messages_lt_LT.json
Labels: release :package:

#1517 fix: update getter to get function
  client/app/billing/autoRenew/disable/disable.controller.js
  client/app/billing/autoRenew/enable/enable.controller.js
  client/app/models/BillingService.class.js
Labels: bug

#1541 feat(mfa): disable cancel action when forced
  client/app/account/user/security/2fa/user-security-2fa.controller.js
  client/app/account/user/security/2fa/user-security-2fa.html
Labels: enhancement

#1546 fix(deps): upgrade @ovh-ux/ng-ovh-otrs to v7.1.12
  package.json
  yarn.lock
Labels: bug

#1501 fix(dedicated-netboot): fix text
  client/app/dedicated/server/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required
