Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2019-01, with the labels that each got.

#851 refactor(components.chartjs): replace by wucChartjs
  client/app/components/chartjs/chartjs.constant.js
  client/app/components/chartjs/chartjs.directive.js
  client/app/components/chartjs/chartjs.factory.js
  client/app/components/chartjs/chartjs.html
Labels: enhancement, one-manager, quality check ok

#883 Fix/order invoices
  client/app/account/billing/orders/billing-orders.html
Labels: bug, quality check ok

#886 build(eslint): use eslint-formatter-pretty
  package.json
  yarn.lock
Labels: enhancement

#850 refactor(components.api): replace with wucApi
  client/app/account/otrs/new-ticket/otrs-new-ticket.service.js
  client/app/components/api/Api.js
  client/app/dedicated/server/dedicated-server.service.js
  client/app/license/license.service.js
Labels: enhancement, one-manager, quality check, quality check ok

#887 fix(billing.autorenew): fix autorenew activation button display
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
Labels: bug, quality check ok

#854 refactor(components.duration): replace with wucDuration
  client/app/app.js
  client/app/components/duration/durationFilter.js
  client/app/dedicated/server/bandwidth-vrack/order/dedicated-server-bandwidth-vrack-order.html
  client/app/dedicated/server/bandwidth/order/dedicated-server-bandwidth-order.html
  client/app/dedicated/server/kvm/order/dedicated-server-kvm-order.html
  client/app/dedicated/server/pro-use/order/dedicated-server-pro-use-order.html
  client/app/dedicated/server/traffic/order/dedicated-server-traffic-order.html
  client/app/dedicated/server/usb-storage/order/dedicated-server-usb-storage-order.html
  client/app/dedicatedCloud/resource/upgrade/dedicatedCloud-resource-upgrade.html
  client/app/ip/ip/order/durations.html
  client/app/ip/ip/order/migrate/ip-ip-order-migrate.html
  client/app/license/order/license-order.html
  client/app/license/upgrade/license-upgrade.html
Labels: enhancement, one-manager, quality check ok

#890 Feat/billing debt nic
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
  client/app/account/billing/autoRenew/domain/billing-autoRenew-domain.html
  client/app/account/billing/autoRenew/hosting/billing-autoRenew-hosting.html
  client/app/account/billing/autoRenew/warnNicBilling/billing-autoRenew-warnNicBilling.controller.js
  client/app/account/billing/autoRenew/warnNicBilling/billing-autoRenew-warnNicBilling.html
  client/app/account/billing/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#882 fix(vantiv): increasing the value of numYears to be 10 at a time
  client/app/components/paymentMethod/vantiv/billing-vantiv.factory.js
  yarn.lock
Labels: bug, quality check ok

#893 fix(guide-link-fix): fix guide links
  client/app/config/constants.config.js
Labels: bug, quality check ok

#901 fix(server): mrtg chart labels
  client/app/dedicated/server/statistics/dedicated-server-statistics.controller.js
Labels: bug, quality check ok

#902 Fix/Billing autorenew exchange: fix resiliation for exchange services
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
Labels: bug, quality check ok

#904 Fix/billing duedate display
  client/app/account/billing/main/history/billing-main-history.html
Labels: bug, quality check ok

#903 fix/billing.autorenew change redirection for exchange dedicated offers
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
Labels: bug, quality check ok

#907 fix(i18n): retrieve translations
  client/app/account/billing/payment/method/edit/translations/Messages_pt_PT.xml
  client/app/account/billing/translations/Messages_cs_CZ.xml
  client/app/account/billing/translations/Messages_de_DE.xml
  client/app/account/billing/translations/Messages_en_ASIA.xml
  client/app/account/billing/translations/Messages_en_AU.xml
  client/app/account/billing/translations/Messages_en_CA.xml
  client/app/account/billing/translations/Messages_en_GB.xml
  client/app/account/billing/translations/Messages_en_SG.xml
  client/app/account/billing/translations/Messages_en_US.xml
  client/app/account/billing/translations/Messages_es_ES.xml
  client/app/account/billing/translations/Messages_es_US.xml
  client/app/account/billing/translations/Messages_fi_FI.xml
  client/app/account/billing/translations/Messages_fr_CA.xml
  client/app/account/billing/translations/Messages_it_IT.xml
  client/app/account/billing/translations/Messages_lt_LT.xml
  client/app/account/billing/translations/Messages_nl_NL.xml
  client/app/account/billing/translations/Messages_pl_PL.xml
  client/app/account/billing/translations/Messages_pt_PT.xml
  client/app/account/otrs/translations/Messages_es_US.xml
  client/app/account/user/newAccountForm/translations/Messages_es_ES.xml
  client/app/account/user/newAccountForm/translations/Messages_es_US.xml
  client/app/account/user/security/users/translations/Messages_es_US.xml
  client/app/account/user/translations/Messages_es_US.xml
  client/app/common/translations/Messages_es_ES.xml
  client/app/common/translations/Messages_es_US.xml
  client/app/components/sidebar-menu/translations/Messages_es_US.xml
  client/app/components/sidebar-menu/translations/Messages_fr_CA.xml
  client/app/components/translations/Messages_es_ES.xml
  client/app/dedicated/housing/translations/Messages_es_US.xml
  client/app/dedicated/server/translations/Messages_es_US.xml
  client/app/dedicated/server/translations/Messages_fr_CA.xml
  client/app/dedicatedCloud/translations/Messages_es_ES.xml
  client/app/dedicatedCloud/translations/Messages_es_US.xml
  client/app/dedicatedCloud/translations/Messages_it_IT.xml
  client/app/dedicatedCloud/translations/Messages_pl_PL.xml
  client/app/dedicatedCloud/translations/Messages_pt_PT.xml
  client/app/dedicatedUniverseComponents/bandwidth/translations/Messages_es_US.xml
  client/app/dedicatedUniverseComponents/bytes/translations/Messages_es_US.xml
  client/app/ip/translations/Messages_es_US.xml
  client/app/ip/translations/Messages_fr_CA.xml
  client/app/license/translations/Messages_es_US.xml
  client/app/user-contracts/translations/Messages_es_US.xml
Labels: bug

#916 fix: prevent loading angularjs more than once
  client/app/account/billing/payment/billing-payment.routes.js
  client/app/account/billing/payment/credits/billing-payment-credits.routes.js
  client/app/account/billing/payment/credits/movements/billing-payment-credits-movements.routes.js
  client/app/account/billing/payment/fidelity/billing-payment-fidelity.routes.js
  client/app/account/billing/payment/method/add/billing-payment-method-add.routes.js
  client/app/account/billing/payment/method/billing-payment-method.controller.js
  client/app/account/billing/payment/method/billing-payment-method.routes.js
  client/app/account/billing/payment/ovhAccount/billing-payment-ovhAccount.routes.js
  client/app/account/billing/payment/refunds/billing-payment-refunds.routes.js
  client/app/account/billing/payment/transactions/billing-payment-transactions.routes.js
  client/app/account/billing/payment/vouchers/billing-payment-voucher.routes.js
  client/app/account/billing/payment/vouchers/movements/billing-payment-vouchers-movements.routes.js
Labels: bug

#919 fix: billingMean injection in autorenew view
  client/app/account/billing/autoRenew/billing-autoRenew.html
  client/app/account/billing/autoRenew/warnPaymentMean/billing-autoRenew-warnPaymentMean.controller.js
  client/app/account/billing/main/history/balance/billing-history-balance.controller.js
  client/app/account/billing/main/history/balance/billing-history-balance.html
  client/app/account/billing/mean/billing-mean.service.js
  client/app/account/billing/paymentMethod/billing-paymentMethod.service.js
Labels: bug

#923 Bugfix/mbe 70 delete shh key
  client/app/account/user/ssh/user-ssh.service.js
Labels: bug, quality check ok

#905 fix(billing-autorenew): payment frequency table header rearrange
  client/app/account/billing/autoRenew/update/billing-autoRenew-update.html
Labels: bug, quality check ok

#925 fix(dedicated.server): infinite loading when installation error
  client/app/dedicated/server/dedicated-server.controller.js
Labels: bug

#921 fix(dedicated): fix ip modal
  client/app/ip/ip/order/PCC.html
Labels: bug, quality check ok

#866 Fix/fr welcome page
  client/app/common/translations/Messages_fr_FR.xml
  client/app/configuration/configuration.component.js
  client/app/configuration/configuration.controller.js
  client/app/configuration/configuration.html
  client/app/configuration/configuration.routes.js
Labels: bug, quality check ok, translation required

#937 Bugfix/mbe 238 move ip
  client/app/ip/ip/block/move/ip-ip-block-move.html
Labels: bug, quality check ok

#939 Upgrade web universe components
  package.json
  yarn.lock
Labels: enhancement

#940 build(deps): upgrade ovh-module-exchange to v9.2.5
  package.json
  yarn.lock
Labels: enhancement

#941 Feat/kube change contacts
  client/app/account/user/contacts/user-contacts.service.js
  client/app/account/user/translations/Messages_fr_FR.xml
Labels: feature, quality check ok

#945 fix(account.billing.payment.add): us payment add
  package.json
  yarn.lock
Labels: bug

#944 fix(dedicated.server): display tabs on reinstall error
  client/app/dedicated/server/dedicated-server.controller.js
Labels: bug, quality check

#947 build(deps): upgrade ovh-module-exchange to v9.3.0
  package.json
  yarn.lock
Labels: enhancement
