Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2019-04, with the labels that each got.

#1042 fix(i18n): retrieve translations
  client/app/account/billing/translations/Messages_de_DE.xml
  client/app/account/user/newAccountForm/translations/Messages_fr_CA.xml
  client/app/account/user/translations/Messages_fr_CA.xml
  client/app/common/translations/Messages_nl_NL.xml
Labels: bug

#1043 refactor(datacenter.drp): use of lodash flatten method
  client/app/dedicatedCloud/datacenter/drp/steps/ovh/secondPcc/dedicatedCloud-datacenter-drp-ovh-secondPccStep.controller.js
Labels: enhancement

#1044 fix(datacenter.drp): disable zerto for us
  client/app/dedicatedCloud/datacenter/dedicatedCloud-datacenter.controller.js
  client/app/dedicatedCloud/datacenter/dedicatedCloud-datacenter.html
  client/app/dedicatedCloud/datacenter/drp/index.js
Labels: bug

#1045 fix(config): remove sk_SK from language constants
  client/app/config/constants.config.js
Labels: bug

#1048 fix(dedicatedcloud.security): fix missing translation
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#1049 fix(i18n): retrieve translations
  client/app/dedicatedCloud/translations/Messages_cs_CZ.xml
  client/app/dedicatedCloud/translations/Messages_de_DE.xml
  client/app/dedicatedCloud/translations/Messages_en_ASIA.xml
  client/app/dedicatedCloud/translations/Messages_en_AU.xml
  client/app/dedicatedCloud/translations/Messages_en_CA.xml
  client/app/dedicatedCloud/translations/Messages_en_GB.xml
  client/app/dedicatedCloud/translations/Messages_en_SG.xml
  client/app/dedicatedCloud/translations/Messages_en_US.xml
  client/app/dedicatedCloud/translations/Messages_es_ES.xml
  client/app/dedicatedCloud/translations/Messages_es_US.xml
  client/app/dedicatedCloud/translations/Messages_fi_FI.xml
  client/app/dedicatedCloud/translations/Messages_fr_CA.xml
  client/app/dedicatedCloud/translations/Messages_it_IT.xml
  client/app/dedicatedCloud/translations/Messages_lt_LT.xml
  client/app/dedicatedCloud/translations/Messages_nl_NL.xml
  client/app/dedicatedCloud/translations/Messages_pl_PL.xml
  client/app/dedicatedCloud/translations/Messages_pt_PT.xml
  client/app/ip/translations/Messages_cs_CZ.xml
  client/app/ip/translations/Messages_de_DE.xml
  client/app/ip/translations/Messages_en_ASIA.xml
  client/app/ip/translations/Messages_en_AU.xml
  client/app/ip/translations/Messages_en_CA.xml
  client/app/ip/translations/Messages_en_GB.xml
  client/app/ip/translations/Messages_en_SG.xml
  client/app/ip/translations/Messages_en_US.xml
  client/app/ip/translations/Messages_es_ES.xml
  client/app/ip/translations/Messages_es_US.xml
  client/app/ip/translations/Messages_fi_FI.xml
  client/app/ip/translations/Messages_fr_CA.xml
  client/app/ip/translations/Messages_it_IT.xml
  client/app/ip/translations/Messages_lt_LT.xml
  client/app/ip/translations/Messages_nl_NL.xml
  client/app/ip/translations/Messages_pl_PL.xml
  client/app/ip/translations/Messages_pt_PT.xml
Labels: bug

#1050 fix(datacenter.drp): remove debug remains
  client/app/dedicatedCloud/datacenter/drp/dedicatedCloud-datacenter-drp.html
Labels: bug

#1051 docs(contributing): remove signed commit requirements
  CONTRIBUTING.md
Labels: enhancement

#1057 fix(datacenter.drp): fix success message
  client/app/dedicatedCloud/datacenter/drp/dedicatedCloud-datacenter-drp.constants.js
  client/app/dedicatedCloud/datacenter/drp/dedicatedCloud-datacenter-drp.service.js
  client/app/dedicatedCloud/datacenter/drp/steps/common/confirmation/dedicatedCloud-datacenter-drp-confirmationStep.controller.js
Labels: bug, quality check ok

#1063 fix(ip.legacy-order): display the right country label
  client/app/ip/ip/legacyOrder/DEDICATED.html
Labels: bug, quality check ok

#1014 fix(ip): fix broken linked services ip order agora
  client/app/ip/ip/agoraOrder/ip-ip-agoraOrder.controller.js
  client/app/ip/ip/order/DEDICATED.html
  client/app/ip/ip/order/PCC.html
  client/app/ip/ip/order/VPS.html
  client/app/ip/ip/order/durations.html
  client/app/ip/ip/order/durationsPCC.html
  client/app/ip/ip/order/ip-ip-order.controller.js
  client/app/ip/ip/order/ip-ip-order.html
  client/app/ip/ip/order/ip-ip-order.service.js
  client/app/ip/ip/order/migrate/ip-ip-order-migrate.controller.js
  client/app/ip/ip/order/migrate/ip-ip-order-migrate.html
  client/app/translations/Messages_fr_FR.xml
Labels: feature, quality check ok, translation required

#1071 fix(ip.order): set a default quantity for express order
  client/app/ip/ip/agoraOrder/ip-ip-agoraOrder.controller.js
Labels: bug

#1070 feat(datacenter.drp): show service name if no description
  client/app/dedicatedCloud/datacenter/drp/steps/common/mainPcc/dedicatedCloud-datacenter-drp-mainPccStep.html
Labels: enhancement, quality check ok

#1075 feat(chatbot): open the chatbot from the assistance menu
  client/app/app.js
  client/app/components/sidebar-menu/translations/Messages_fr_FR.xml
  client/app/components/user/session/user-session.service.js
  client/app/index.html
  package.json
  yarn.lock
Labels: feature, quality check ok

#1080 build(deps): upgrade both ovh-ui-angular and ovh-ui-kit dependencies
  package.json
  yarn.lock
Labels: enhancement

#1082 fix(i18n): retrieve translations
  client/app/components/sidebar-menu/translations/Messages_cs_CZ.xml
  client/app/components/sidebar-menu/translations/Messages_de_DE.xml
  client/app/components/sidebar-menu/translations/Messages_en_ASIA.xml
  client/app/components/sidebar-menu/translations/Messages_en_AU.xml
  client/app/components/sidebar-menu/translations/Messages_en_CA.xml
  client/app/components/sidebar-menu/translations/Messages_en_GB.xml
  client/app/components/sidebar-menu/translations/Messages_en_SG.xml
  client/app/components/sidebar-menu/translations/Messages_en_US.xml
  client/app/components/sidebar-menu/translations/Messages_es_ES.xml
  client/app/components/sidebar-menu/translations/Messages_es_US.xml
  client/app/components/sidebar-menu/translations/Messages_fi_FI.xml
  client/app/components/sidebar-menu/translations/Messages_fr_CA.xml
  client/app/components/sidebar-menu/translations/Messages_it_IT.xml
  client/app/components/sidebar-menu/translations/Messages_lt_LT.xml
  client/app/components/sidebar-menu/translations/Messages_nl_NL.xml
  client/app/components/sidebar-menu/translations/Messages_pl_PL.xml
  client/app/components/sidebar-menu/translations/Messages_pt_PT.xml
Labels: bug

#1083 build(deps): upgrade @ovh-ux/ng-ovh-chatbot to v2.0.0
  package.json
  yarn.lock
Labels: enhancement

#1088 fix(i18n): retrieve translations
  client/app/components/sidebar-menu/translations/Messages_en_ASIA.xml
  client/app/components/sidebar-menu/translations/Messages_en_AU.xml
  client/app/components/sidebar-menu/translations/Messages_en_CA.xml
  client/app/components/sidebar-menu/translations/Messages_en_GB.xml
  client/app/components/sidebar-menu/translations/Messages_en_SG.xml
  client/app/components/sidebar-menu/translations/Messages_en_US.xml
Labels: bug

#1089 fix(components.user.session): remove duplicate ticket entry
  client/app/components/user/session/user-session.service.js
Labels: bug, quality check ok

#1091 Feat/dedicated server rdv
  client/app/dedicated/server/dedicated-server.controller.js
  client/app/dedicated/server/rendezvous/dedicated-server-rendezvous.controller.js
  client/app/dedicated/server/rendezvous/dedicated-server-rendezvous.html
  client/app/dedicated/server/rendezvous/dedicated-server-rendezvous.routes.js
  client/app/images/rendezvous.svg
Labels: feature, quality check ok
