Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2019-08, with the labels that each got.

#1280 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1255 feat(billing.autorenew): remove HOSTING_DOMAIN grouping
  client/app/account/billing/autoRenew/billing-autoRenew.html
  client/app/account/billing/autoRenew/billing-autoRenew.service.js
  client/app/account/billing/autoRenew/domain/billing-autoRenew-domain.html
Labels: feature, quality check ok

#1281 refactor(app): hide preload on transition finish
  client/app/account/account.routes.js
  client/app/app.controller.js
  client/app/app.js
  client/app/app.routes.js
  client/app/components/manager-preload/manager-preload.less
  client/app/components/manager-preload/manager-preload.module.js
  client/app/css/source.less
  webpack.config.js
Labels: enhancement, quality check ok

#1287 Release v10.21.0
  client/app/account/account.routes.js
  client/app/account/billing/autoRenew/billing-autoRenew.html
  client/app/account/billing/autoRenew/billing-autoRenew.service.js
  client/app/account/billing/autoRenew/domain/billing-autoRenew-domain.html
  client/app/app.controller.js
  client/app/app.js
  client/app/app.routes.js
  client/app/components/manager-preload/manager-preload.less
  client/app/components/manager-preload/manager-preload.module.js
  client/app/css/source.less
  client/app/dedicated/server/translations/Messages_es_ES.json
  client/app/dedicatedUniverseComponents/price/price.filter.js
  client/app/dedicatedUniverseComponents/price/translations/Messages_fr_FR.json
  client/app/error/translations/Messages_de_DE.json
  client/app/error/translations/Messages_it_IT.json
  client/app/error/translations/Messages_pl_PL.json
  client/app/error/translations/Messages_pt_PT.json
  client/app/ip/ip/reverse/add/ip-ip-reverse-add.html
  client/app/ip/ip/reverse/update/translations/Messages_en_ASIA.json
  client/app/ip/ip/reverse/update/translations/Messages_en_AU.json
  client/app/ip/ip/reverse/update/translations/Messages_en_CA.json
  client/app/ip/ip/reverse/update/translations/Messages_en_GB.json
  client/app/ip/ip/reverse/update/translations/Messages_en_SG.json
  client/app/ip/ip/reverse/update/translations/Messages_en_US.json
  client/app/ip/ip/reverse/update/translations/Messages_fi_FI.json
  client/app/ip/ip/reverse/update/translations/Messages_lt_LT.json
  client/app/ip/translations/Messages_de_DE.json
  client/app/ip/translations/Messages_es_ES.json
  client/app/ip/translations/Messages_fr_FR.json
  client/app/ip/translations/Messages_it_IT.json
  client/app/ip/translations/Messages_pl_PL.json
  client/app/ip/translations/Messages_pt_PT.json
  package.json
  webpack.config.js
  yarn.lock
Labels: release :package:

#1279 feat(app): update and use error page
  client/app/app.js
  client/app/error/error.component.js
  client/app/error/error.controller.js
  client/app/error/error.html
  client/app/error/error.module.js
  client/app/error/error.routes.js
  client/app/error/error.routing.js
  client/app/error/translations/Messages_fr_FR.json
Labels: feature, quality check ok, translation required

#1270 feat: use ng-ui-router-line-progress
  client/app/app.js
  client/app/app.less
  client/app/index.html
  package.json
  yarn.lock
Labels: dependencies, enhancement

#1303 fix(dedicatedcloud.dashboard.options): disable some actions
  client/app/dedicatedCloud/dashboard/options/options.html
Labels: bug, quality check ok

#1286 fix(support): fix support status text error
  client/app/account/otrs/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required

#1248 feat(dedicated.server): add upgrade link with tracking
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/dedicated/server/dedicated-server.contants.js
  client/app/dedicated/server/dedicated-server.controller.js
  client/app/dedicated/server/dedicated-server.service.js
  client/app/dedicated/server/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: feature, quality check ok, translation required

#1304 fix(billing.autorenew): allow autorenew activation for some subs
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/billing-autoRenew.html
  client/app/account/billing/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required

#1307 fix(dedicated.server.traffic): use correct filter name
  client/app/dedicated/server/traffic/dedicated-server-traffic.service.js
Labels: bug, quality check ok

#1308 feat(billing.autorenew): remove HOSTING_DOMAIN grouping
  client/app/account/billing/autoRenew/billing-autoRenew.html
  client/app/account/billing/autoRenew/billing-autoRenew.service.js
  client/app/account/billing/autoRenew/domain/billing-autoRenew-domain.html
Labels: feature

#1311 build(webpack): remove resolve.symlinks options
  webpack.config.js
Labels: build

#1316 fix: update manager urls
  client/app/account/user/ssh/user-ssh.service.js
  client/app/config/constants.config.js
Labels: bug

#1318 fix(deps): upgrade ng-ovh-otrs to v7.1.10
  package.json
  yarn.lock
Labels: bug

#1315 fix(sidebar): use nasha from cloud manager
  package.json
  yarn.lock
Labels: bug

#1244 feat(dedicated.server): disable firewall and backup section in US
  client/app/dedicated/server/dedicated-server.html
  client/app/dedicated/server/firewall/dedicated-server-firewall.routes.js
  client/app/dedicated/server/ftp-backup/dedicated-server-ftp-backup.routes.js
Labels: enhancement

#1321 feat: add @ovh-ux/ng-ovh-request-tagger
  package.json
  yarn.lock
Labels: enhancement

#1285 Feat/handle vantiv payment method type
  client/app/account/billing/payment/method/add/billing-payment-method-add.controller.js
  client/app/account/billing/payment/method/add/billing-payment-method-add.html
  client/app/account/billing/payment/method/billing-payment-method.html
  client/app/app.js
  client/app/components/paymentMethod/services/billing-payment-method.constant.js
  client/app/components/paymentMethod/services/billing-payment-method.service.js
  client/app/components/paymentMethod/services/me-payment-method.service.js
  client/app/components/paymentMethod/vantiv/billing-vantiv-configurator.provider.js
  client/app/components/paymentMethod/vantiv/billing-vantiv-instance.service.js
  client/app/components/paymentMethod/vantiv/billing-vantiv.constants.js
  client/app/components/paymentMethod/vantiv/billing-vantiv.factory.js
  package.json
  yarn.lock
Labels: enhancement, quality check ok

#1325 Release v10.24.0
  client/app/account/billing/payment/method/add/billing-payment-method-add.controller.js
  client/app/account/billing/payment/method/add/billing-payment-method-add.html
  client/app/account/billing/payment/method/billing-payment-method.html
  client/app/app.js
  client/app/components/paymentMethod/services/billing-payment-method.constant.js
  client/app/components/paymentMethod/services/billing-payment-method.service.js
  client/app/components/paymentMethod/services/me-payment-method.service.js
  client/app/components/paymentMethod/vantiv/billing-vantiv-configurator.provider.js
  client/app/components/paymentMethod/vantiv/billing-vantiv-instance.service.js
  client/app/components/paymentMethod/vantiv/billing-vantiv.constants.js
  client/app/components/paymentMethod/vantiv/billing-vantiv.factory.js
  package.json
  yarn.lock
Labels: release :package:

#1331 Feat/dedicated servers
  client/app/app.js
  client/app/dedicated/server/servers/servers.component.js
  client/app/dedicated/server/servers/servers.controller.js
  client/app/dedicated/server/servers/servers.html
  client/app/dedicated/server/servers/servers.module.js
  client/app/dedicated/server/servers/servers.routing.js
  client/app/dedicated/server/servers/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: feature, quality check ok

#1332 feat(dedicated.servers): add order tracker
  client/app/dedicated/server/servers/servers.html
Labels: feature, quality check ok

#1317 fix(ip): fix game names in ip config
  client/app/ip/ip/firewall/game/ip-ip-firewall-game.constants.js
  client/app/ip/ip/firewall/game/rule/add/ip-ip-firewall-game-rule-add.controller.js
  client/app/ip/translations/Messages_de_DE.json
  client/app/ip/translations/Messages_en_GB.json
  client/app/ip/translations/Messages_es_ES.json
  client/app/ip/translations/Messages_es_US.json
  client/app/ip/translations/Messages_fi_FI.json
  client/app/ip/translations/Messages_fr_CA.json
  client/app/ip/translations/Messages_fr_FR.json
  client/app/ip/translations/Messages_it_IT.json
  client/app/ip/translations/Messages_lt_LT.json
  client/app/ip/translations/Messages_nl_NL.json
  client/app/ip/translations/Messages_pl_PL.json
  client/app/ip/translations/Messages_pt_PT.json
Labels: bug, quality check ok

#1337 refactor(dedicated.server.servers): replace some deprecated stateParams
  client/app/dedicated/server/servers/servers.routing.js
Labels: enhancement

#1333 fix(dedicated.servers): reset page number when filtering
  client/app/dedicated/server/servers/servers.routing.js
Labels: bug

#1336 feat(billing.payment.method): re-enable contactId for VANTIV_IFRAME
  client/app/account/billing/payment/method/add/billing-payment-method-add.controller.js
  client/app/account/billing/payment/method/add/billing-payment-method-add.html
  package.json
  yarn.lock
Labels: feature, quality check ok

#1342 Release v10.25.1
  client/app/dedicated/server/servers/translations/Messages_en_GB.json
  client/app/dedicated/server/servers/translations/Messages_fi_FI.json
  client/app/dedicated/server/servers/translations/Messages_fr_CA.json
  client/app/dedicated/server/servers/translations/Messages_lt_LT.json
Labels: release :package:

#1338 Fix/autorenew
  client/app/billing/autoRenew/BillingService.class.js
  client/app/billing/autoRenew/actions/update/automatic/automatic.component.js
  client/app/billing/autoRenew/actions/update/automatic/automatic.html
  client/app/billing/autoRenew/actions/update/automatic/translations/Messages_fr_FR.json
  client/app/billing/autoRenew/actions/update/form/form.controller.js
  client/app/billing/autoRenew/actions/update/manualPayment/translations/Messages_fr_FR.json
  client/app/billing/autoRenew/actions/update/update.html
  client/app/billing/autoRenew/autorenew.controller.js
  client/app/billing/autoRenew/autorenew.html
  client/app/billing/autoRenew/autorenew.routing.js
  client/app/billing/autoRenew/disable/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: bug, quality check ok

#1348 fix(billing.autorenew): handle if autorenew has never been active
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/billing-autoRenew.html
Labels: bug, quality check ok

#1352 build(deps): upgrade ng-ovh-sso-auth to v4.2.0
  package.json
  yarn.lock
Labels: dependencies

#1353 feat(billing.autorenew): add tracking
  client/app/billing/autoRenew/actions/activation/activation.controller.js
  client/app/billing/autoRenew/actions/cancel-resiliation/cancel-resiliation.controller.js
  client/app/billing/autoRenew/actions/debtBeforePaying/debtBeforePaying.routing.js
  client/app/billing/autoRenew/actions/delete/billing-autoRenew-delete.controller.js
  client/app/billing/autoRenew/actions/terminate/terminate.controller.js
  client/app/billing/autoRenew/actions/update/update.controller.js
  client/app/billing/autoRenew/actions/update/update.html
Labels: feature, quality check ok

#1355 docs: remove CODE_OF_CONDUCT.md file.
  CODE_OF_CONDUCT.md
Labels: documentation

#1357 fix(billing.autorenew): correct transation
  client/app/billing/autoRenew/disable/translations/Messages_fr_FR.json
Labels: bug, translation required

#1361 build(package.json): bump ng-ovh-sso-auth to v4.2.1
  package.json
  yarn.lock
Labels: dependencies

#1365 build: bump ovh-ui-angular to v3.7.4
  package.json
  yarn.lock
Labels: dependencies

#1363 feat(billing.users.contracts): add a link for details of agreements
  client/app/billing/autoRenew/agreements/details/user-agreements-details.controller.js
  client/app/billing/autoRenew/agreements/details/user-agreements-details.html
  client/app/billing/autoRenew/agreements/translations/Messages_fr_FR.json
  client/app/billing/autoRenew/agreements/user-agreements.constant.js
Labels: quality check

#1354 fix(otrs): disable service types unavailable
  package.json
  yarn.lock
Labels: bug, quality check ok

#1367 fix: remove console.log
  client/app/app.js
Labels: bug
