Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2019-03, with the labels that each got.

#986 fix(billing): track billing
  client/app/account/billing/main/history/debt/pay/billing-main-history-debt-pay.controller.js
Labels: bug, quality check ok

#982 feat(cdn.dedicated): expose logs to customers
  client/app/app.js
  client/app/cdn/dedicated/domain/cdn-dedicated-domain.html
  client/app/cdn/dedicated/domain/logs/cdn-dedicated-domain-logs.controller.js
  client/app/cdn/dedicated/domain/logs/cdn-dedicated-domain-logs.html
  client/app/cdn/dedicated/domain/logs/cdn-dedicated-domain-logs.routes.js
  client/app/cdn/dedicated/manage/cdn-dedicated-manage.html
  client/app/cdn/dedicated/manage/logs/cdn-dedicated-manage-logs.controller.js
  client/app/cdn/dedicated/manage/logs/cdn-dedicated-manage-logs.html
  client/app/cdn/dedicated/manage/logs/cdn-dedicated-manage-logs.routes.js
  client/app/cdn/dedicated/translations/Messages_fr_FR.xml
  client/app/css/source.less
  client/app/index.js
  package.json
  yarn.lock
Labels: feature, quality check ok, translation required

#995 fix(deps): upgrade ovh-module-exchange to v9.3.3
  package.json
  yarn.lock
Labels: enhancement

#994 build(deps): upgrade ng-ovh-swimming-poll to v4.0.0
  client/app/app.js
  client/app/dedicatedUniverseComponents/bandwidth/index.js
  client/app/dedicatedUniverseComponents/bytes/index.js
  client/app/dedicatedUniverseComponents/contract/index.js
  client/app/dedicatedUniverseComponents/notification/index.js
  client/app/dedicatedUniverseComponents/price/index.js
  client/app/dedicatedUniverseComponents/tabs/index.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#1004 fix(cdn): fix chart data
  client/app/cdn/dedicated/manage/statistics/cdn-dedicated-manage-statistics.controller.js
Labels: bug, quality check ok

#997 build(deps): upgrade ng-ovh-api-wrappers
  client/app/app.js
  package.json
  yarn.lock
Labels: enhancement, quality check ok

#1005 fix(deps): upgrade ng-at-internet to v4.0.0
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#1011 fix(deps): upgrade ovh-api-services to v6.1.2
  package.json
  yarn.lock
Labels: bug

#984 fix(server-mrtg): error on graph data load
  client/app/dedicated/server/statistics/dedicated-server-statistics.controller.js
Labels: bug, quality check ok

#1007 fix(dedicated): change some zerto translations
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: translation required

#1001 fix: otrs module upgrade
  client/app/account/otrs/translations/Messages_cs_CZ.xml
  client/app/account/otrs/translations/Messages_de_DE.xml
  client/app/account/otrs/translations/Messages_en_ASIA.xml
  client/app/account/otrs/translations/Messages_en_AU.xml
  client/app/account/otrs/translations/Messages_en_CA.xml
  client/app/account/otrs/translations/Messages_en_GB.xml
  client/app/account/otrs/translations/Messages_en_SG.xml
  client/app/account/otrs/translations/Messages_en_US.xml
  client/app/account/otrs/translations/Messages_es_ES.xml
  client/app/account/otrs/translations/Messages_es_US.xml
  client/app/account/otrs/translations/Messages_fi_FI.xml
  client/app/account/otrs/translations/Messages_fr_CA.xml
  client/app/account/otrs/translations/Messages_fr_FR.xml
  client/app/account/otrs/translations/Messages_it_IT.xml
  client/app/account/otrs/translations/Messages_lt_LT.xml
  client/app/account/otrs/translations/Messages_nl_NL.xml
  client/app/account/otrs/translations/Messages_pl_PL.xml
  client/app/account/otrs/translations/Messages_pt_PT.xml
  client/app/app.js
  client/app/components/ovh-angular-otrs/ovh-angular-otrs.js
  client/app/css/source.less
  client/app/index.js
  package.json
  yarn.lock
Labels: bug, quality check ok

#1017 [Support new order funnel - Part 1] Refactoring dependency handling
  client/app/account/billing/billingApp.module.js
  client/app/app.js
Labels: enhancement, quality check ok

#1018 [Support new order funnel - Part 2] Miscellaneous fixes for Dedicated
  client/app/app.routes.js
  client/app/common/translations/Messages_fr_FR.xml
  client/app/dedicatedCloud/datacenter/1000-v/dedicatedCloud-datacenter-1000-v.html
  client/app/dedicatedCloud/dedicatedCloud.controller.js
  client/app/dedicatedCloud/dedicatedCloud.html
  client/app/dedicatedCloud/security/access/dedicatedCloud-security-access.controller.js
  client/app/dedicatedCloud/security/add/dedicatedCloud-security-add.controller.js
  client/app/dedicatedCloud/security/dedicatedCloud-security.html
  client/app/dedicatedCloud/security/logout/dedicatedCloud-security-logout.controller.js
  client/app/dedicatedCloud/security/session-timeout/update/dedicatedCloud-security-session-timeout-update.controller.js
  client/app/dedicatedCloud/security/session-timeout/update/dedicatedCloud-security-session-timeout-update.html
  client/app/dedicatedCloud/security/simultaneous-connection/update/dedicatedCloud-security-max-simultaneous-connection.controller.js
  client/app/dedicatedCloud/security/simultaneous-connection/update/dedicatedCloud-security-max-simultaneous-connection.html
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
  client/app/dedicatedCloud/user/add/dedicatedCloud-user-add.html
  client/app/dedicatedCloud/user/dedicatedCloud-user.html
  client/app/dedicatedCloud/user/delete/dedicatedCloud-user-delete.controller.js
  client/app/dedicatedCloud/user/disable/dedicatedCloud-user-disable.controller.js
  client/app/dedicatedCloud/user/enable/dedicatedCloud-user-enable.controller.js
  client/app/dedicatedCloud/vmware-option/dedicatedCloud-vmware-option.controller.js
  client/app/images/btn/Icone-btn-1000v.png
  client/app/ip/translations/Messages_fr_FR.xml
Labels: bug, enhancement, quality check ok, translation required

#1022 [Support new order funnel - Part 3] Miscellaneous fixes for Dedicated Datacenter
  client/app/components/name-edition/name-edition.controller.js
  client/app/dedicatedCloud/datacenter/backup/dedicatedCloud-datacenter-backup.controller.js
  client/app/dedicatedCloud/datacenter/backup/dedicatedCloud-datacenter-backup.routes.js
  client/app/dedicatedCloud/datacenter/backup/disable/dedicatedCloud-datacenter-backup-disable.controller.js
  client/app/dedicatedCloud/datacenter/backup/enable/dedicatedCloud-datacenter-backup-enable.controller.js
  client/app/dedicatedCloud/datacenter/backup/enable/dedicatedCloud-datacenter-backup-enable.routes.js
  client/app/dedicatedCloud/datacenter/backup/enableAgora/dedicatedCloud-datacenter-backup-enableAgora.controller.js
  client/app/dedicatedCloud/datacenter/datastore/dedicatedCloud-datacenter-datastore.controller.js
  client/app/dedicatedCloud/datacenter/datastore/dedicatedCloud-datacenter-datastore.html
  client/app/dedicatedCloud/datacenter/datastore/orderUS/dedicatedCloud-datacenter-datastore-orderUS.controller.js
  client/app/dedicatedCloud/datacenter/dedicatedCloud-datacenter.constants.js
  client/app/dedicatedCloud/datacenter/dedicatedCloud-datacenter.controller.js
  client/app/dedicatedCloud/datacenter/dedicatedCloud-datacenter.html
  client/app/dedicatedCloud/datacenter/dedicatedCloud-datacenter.routes.js
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.controller.js
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.html
  client/app/dedicatedCloud/datacenter/host/dedicatedCloud-datacenter-host.routes.js
  client/app/dedicatedCloud/datacenter/host/orderUS/dedicatedCloud-datacenter-host-orderUS.controller.js
  client/app/dedicatedCloud/dedicatedCloud.controller.js
  client/app/dedicatedCloud/dedicatedCloud.service.js
  client/app/dedicatedCloud/translations/Messages_fr_FR.xml
Labels: bug, enhancement, quality check ok, translation required

#1032 Feat/new dedicated resiliation
  client/app/account/billing/autoRenew/delete/billing-autoRenew-delete.controller.js
  client/app/account/billing/autoRenew/delete/billing-autoRenew-delete.html
  client/app/account/billing/translations/Messages_fr_FR.xml
  client/app/common/translations/Messages_fr_FR.xml
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/dedicated/server/terminate/dedicated-server-terminate.controller.js
  client/app/dedicated/server/terminate/dedicated-server-terminate.html
  client/app/dedicated/server/translations/Messages_fr_FR.xml
Labels: quality check ok

#1030 fix(billing.payment.add): contact choice for ES and IE
  client/app/account/billing/payment/method/add/views/billing-address/add-billing-address.controller.js
  client/app/account/billing/payment/method/add/views/billing-address/add-billing-address.html
  package.json
  yarn.lock
Labels: bug, quality check

#1009 feat(account.billing): add exchange account renew in my services
  client/app/account/billing/autoRenew/billing-autoRenew.controller.js
  client/app/account/billing/autoRenew/billing-autoRenew.service.js
  client/app/account/billing/autoRenew/common/billing-autoRenew-common.html
  client/app/account/billing/autoRenew/exchange/exchange-renew.controller.js
  client/app/account/billing/autoRenew/exchange/exchange-renew.html
  client/app/account/billing/translations/Messages_fr_FR.xml
  package.json
  yarn.lock
Labels: enhancement, quality check ok, translation required
