Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2019-06, with the labels that each got.

#1159 fix(i18n): retrieve translations
  client/app/cdn/dedicated/translations/Messages_en_ASIA.xml
  client/app/cdn/dedicated/translations/Messages_en_AU.xml
  client/app/cdn/dedicated/translations/Messages_en_CA.xml
  client/app/cdn/dedicated/translations/Messages_en_GB.xml
  client/app/cdn/dedicated/translations/Messages_en_SG.xml
  client/app/cdn/dedicated/translations/Messages_en_US.xml
  client/app/cdn/dedicated/translations/Messages_es_ES.xml
  client/app/dedicated/server/translations/Messages_en_ASIA.xml
  client/app/dedicated/server/translations/Messages_en_AU.xml
  client/app/dedicated/server/translations/Messages_en_CA.xml
  client/app/dedicated/server/translations/Messages_en_GB.xml
  client/app/dedicated/server/translations/Messages_en_SG.xml
  client/app/dedicated/server/translations/Messages_en_US.xml
  client/app/dedicated/server/translations/Messages_es_ES.xml
Labels: bug

#1163 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: bug, quality check ok

#1167 fix(i18n): retrieve translations
  client/app/cdn/dedicated/translations/Messages_pl_PL.xml
  client/app/dedicated/housing/translations/Messages_pl_PL.xml
  client/app/dedicated/server/translations/Messages_pl_PL.xml
Labels: bug

#1173 fix(deps): upgrade ng-ovh-otrs to v7.1.1
  package.json
  yarn.lock
Labels: bug

#1176 fix(deps): upgrade ng-ovh-otrs to v7.1.2
  package.json
  yarn.lock
Labels: bug

#1179 fix(deps): upgrade ng-ovh-otrs to v7.1.4
  package.json
  yarn.lock
Labels: bug

#1183 perf: remove duplicate randexp
  .eslintignore
  client/app/index.js
  client/assets/randexp.min.js
  package.json
  yarn.lock
Labels: performance

#1182 build: upgrade @ovh-ux/ng-ovh-web-universe-components@4.0.0
  package.json
  yarn.lock
Labels: dependencies

#1185 feat(dedicated.server): remove useless information network tile
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
Labels: enhancement

#1184 build: bump @ovh-ux/manager-navbar
  package.json
  yarn.lock
Labels: dependencies

#1190 refactor(components): remove unused file for sidebar menu
  client/app/components/ovh-angular-sidebar-menu/ovh-angular-sidebar-menu.module.js
Labels: enhancement

#1189 Fix/pcc arin ip count
  client/app/dedicatedCloud/dashboard/legacy/legacy.html
Labels: bug, quality check ok

#1192 fix(cdn.dedicated.service): return data from getSelected method
  client/app/cdn/dedicated/cdn-dedicated.service.js
Labels: bug

#1196 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1198 fix(billing.autorenew): display alert only if autoRenew is not activated
  client/app/account/billing/autoRenew/billing-autoRenew.html
Labels: bug

#1199 fix(billing.payment.ovhaccount.retrieve): add non valid bank accounts
  client/app/account/billing/payment/ovhAccount/retrieve/billing-ovhAccount-retrieve.controller.js
Labels: bug

#1203 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1195 fix(mrtg-graphic): fix mrtg graphics
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/dedicated/server/dedicated-server.service.js
  client/app/dedicated/server/statistics/dedicated-server-statistics.controller.js
Labels: bug, quality check ok

#1204 Release v10.18.2
  client/app/dedicated/server/dashboard/DASHBOARD_VIEW.html
  client/app/dedicated/server/dedicated-server.service.js
  client/app/dedicated/server/statistics/dedicated-server-statistics.controller.js
  client/app/dedicatedCloud/dashboard/generalInformation/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/options/activationStatus/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/options/order/steps/requiredConfiguration/translations/Messages_en_ASIA.json
  client/app/dedicatedCloud/dashboard/options/order/steps/requiredConfiguration/translations/Messages_en_AU.json
  client/app/dedicatedCloud/dashboard/options/order/steps/requiredConfiguration/translations/Messages_en_CA.json
  client/app/dedicatedCloud/dashboard/options/order/steps/requiredConfiguration/translations/Messages_en_GB.json
  client/app/dedicatedCloud/dashboard/options/order/steps/requiredConfiguration/translations/Messages_en_SG.json
  client/app/dedicatedCloud/dashboard/options/order/steps/requiredConfiguration/translations/Messages_en_US.json
  client/app/dedicatedCloud/dashboard/options/order/steps/requiredConfiguration/translations/Messages_fi_FI.json
  client/app/dedicatedCloud/dashboard/options/order/steps/requiredConfiguration/translations/Messages_lt_LT.json
  client/app/dedicatedCloud/dashboard/options/order/steps/smsActivation/translations/Messages_en_ASIA.json
  client/app/dedicatedCloud/dashboard/options/order/steps/smsActivation/translations/Messages_en_AU.json
  client/app/dedicatedCloud/dashboard/options/order/steps/smsActivation/translations/Messages_en_CA.json
  client/app/dedicatedCloud/dashboard/options/order/steps/smsActivation/translations/Messages_en_GB.json
  client/app/dedicatedCloud/dashboard/options/order/steps/smsActivation/translations/Messages_en_SG.json
  client/app/dedicatedCloud/dashboard/options/order/steps/smsActivation/translations/Messages_en_US.json
  client/app/dedicatedCloud/dashboard/options/order/steps/smsActivation/translations/Messages_fi_FI.json
  client/app/dedicatedCloud/dashboard/options/order/steps/smsActivation/translations/Messages_lt_LT.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_en_ASIA.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_en_AU.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_en_CA.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_en_GB.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_en_SG.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_en_US.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_fi_FI.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_lt_LT.json
  client/app/dedicatedCloud/dashboard/options/order/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/options/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/serviceManagement/translations/Messages_es_ES.json
  client/app/dedicatedCloud/resource/upgrade/translations/Messages_es_ES.json
  package.json
  yarn.lock
Labels: release :package:

#1208 fix(license): add missing translations
  client/app/license/translations/Messages_fr_FR.json
Labels: bug, translation required

#1207 fix(deps): upgrade ng-ovh-otrs to v7.1.5
  package.json
  yarn.lock
Labels: dependencies

#1209 Release v10.18.3
  client/app/license/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: release :package:

#1213 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1216 Release v10.19.1
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_de_DE.json
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_en_ASIA.json
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_en_AU.json
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_en_CA.json
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_en_GB.json
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_en_SG.json
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_en_US.json
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_fi_FI.json
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_lt_LT.json
  client/app/dedicatedCloud/dashboard/options/order/confirm/translations/Messages_pt_PT.json
  client/app/dedicatedCloud/dashboard/options/order/stepper/header/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/options/order/steps/requiredConfiguration/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/options/order/steps/requiredConfiguration/translations/Messages_pt_PT.json
  client/app/dedicatedCloud/dashboard/options/order/steps/selection/translations/Messages_de_DE.json
  client/app/dedicatedCloud/dashboard/options/order/steps/selection/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/options/order/steps/selection/translations/Messages_pt_PT.json
  client/app/dedicatedCloud/dashboard/options/order/steps/smsActivation/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_de_DE.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/options/order/steps/summary/translations/Messages_it_IT.json
  client/app/dedicatedCloud/dashboard/options/servicePack/translations/Messages_de_DE.json
  client/app/dedicatedCloud/dashboard/options/servicePack/translations/Messages_es_ES.json
  client/app/dedicatedCloud/dashboard/options/translations/Messages_it_IT.json
  client/app/dedicatedCloud/dashboard/serviceManagement/translations/Messages_it_IT.json
  client/app/dedicatedCloud/translations/Messages_de_DE.json
  client/app/dedicatedCloud/translations/Messages_en_ASIA.json
  client/app/dedicatedCloud/translations/Messages_en_AU.json
  client/app/dedicatedCloud/translations/Messages_en_CA.json
  client/app/dedicatedCloud/translations/Messages_en_GB.json
  client/app/dedicatedCloud/translations/Messages_en_SG.json
  client/app/dedicatedCloud/translations/Messages_en_US.json
  client/app/dedicatedCloud/translations/Messages_es_ES.json
  client/app/dedicatedCloud/translations/Messages_fi_FI.json
  client/app/dedicatedCloud/translations/Messages_lt_LT.json
  package.json
  yarn.lock
Labels: release :package:

#1219 fix(deps): upgrade ng-ovh-sidebar-menu to v8.3.3
  package.json
  yarn.lock
Labels: bug, quality check ok
