Repository ovh-ux/ovh-manager-dedicated, pull requests merged in 2019-09, with the labels that each got.

#1377 fix: redirect old aurorenew url
  client/app/billing/autoRenew/autorenew.routing.js
Labels: bug

#1380 fix(rtm): add missing lodash import
  client/app/dedicated/server/statistics/rtm/ServerStatsRtmGeneralController.js
Labels: bug

#1379 feat(autorenew): add manual renew action
  client/app/billing/autoRenew/autorenew.constants.js
  client/app/billing/autoRenew/autorenew.controller.js
  client/app/billing/autoRenew/autorenew.html
  client/app/billing/autoRenew/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: feature, quality check ok

#1383 feat: add manager banner
  client/app/app.js
  client/app/configuration/configuration.html
  package.json
  yarn.lock
Labels: quality check ok

#1376 fix(billing): add comments title to confirm terminate page
  client/app/billing/confirmTerminate/billing-confirmTerminate.html
  client/app/billing/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required

#1396 fix(billing.autorenew): display pop up to pay bill
  client/app/billing/autoRenew/autorenew.component.js
  client/app/billing/autoRenew/autorenew.html
  client/app/billing/autoRenew/autorenew.routing.js
Labels: bug, quality check ok

#1400 fix(billing.autorenew): fix bulk enable/disable
  client/app/billing/autoRenew/disable/disable.controller.js
  client/app/billing/autoRenew/enable/enable.controller.js
  client/app/billing/autoRenew/enable/enable.routing.js
Labels: bug

#1403 fix(billing.autorenew): update autorenew activation condition
  client/app/billing/autoRenew/autorenew.html
Labels: bug, quality check ok

#1406 fix(account): set right label for italianSDI field
  client/app/account/user/newAccountForm/translations/Messages_fr_FR.json
  client/app/account/user/newAccountForm/translations/Messages_it_IT.json
Labels: bug

#1411 fix(deps): upgrade ovh-module-exchange to v9.4.8
  package.json
  yarn.lock
Labels: bug, dependencies

#1409 fix(billing): return according capability for resiliated services
  client/app/models/BillingService.class.js
Labels: bug, quality check ok

#1419 build: remove duplicate package
  package.json
  yarn.lock
Labels: build

#1381 Feat/handle vantiv threat metric
  package.json
  yarn.lock
Labels: build, enhancement
